// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface FormatDelimitedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.FormatDelimited)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the source columns name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>repeated .gpss.IntermediateColumn columns = 1;</code>
   */
  java.util.List<gpss.IntermediateColumn> 
      getColumnsList();
  /**
   * <pre>
   * the source columns name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>repeated .gpss.IntermediateColumn columns = 1;</code>
   */
  gpss.IntermediateColumn getColumns(int index);
  /**
   * <pre>
   * the source columns name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>repeated .gpss.IntermediateColumn columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <pre>
   * the source columns name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>repeated .gpss.IntermediateColumn columns = 1;</code>
   */
  java.util.List<? extends gpss.IntermediateColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <pre>
   * the source columns name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>repeated .gpss.IntermediateColumn columns = 1;</code>
   */
  gpss.IntermediateColumnOrBuilder getColumnsOrBuilder(
      int index);

  /**
   * <code>string delimiter = 2;</code>
   * @return The delimiter.
   */
  java.lang.String getDelimiter();
  /**
   * <code>string delimiter = 2;</code>
   * @return The bytes for delimiter.
   */
  com.google.protobuf.ByteString
      getDelimiterBytes();
}
