// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * Protobuf type {@code gpss.FormatJSON}
 */
public final class FormatJSON extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.FormatJSON)
    FormatJSONOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FormatJSON.newBuilder() to construct.
  private FormatJSON(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FormatJSON() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FormatJSON();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FormatJSON(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            gpss.IntermediateColumn.Builder subBuilder = null;
            if (column_ != null) {
              subBuilder = column_.toBuilder();
            }
            column_ = input.readMessage(gpss.IntermediateColumn.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(column_);
              column_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_FormatJSON_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_FormatJSON_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.FormatJSON.class, gpss.FormatJSON.Builder.class);
  }

  public static final int COLUMN_FIELD_NUMBER = 1;
  private gpss.IntermediateColumn column_;
  /**
   * <pre>
   * the source column name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>.gpss.IntermediateColumn column = 1;</code>
   * @return Whether the column field is set.
   */
  @java.lang.Override
  public boolean hasColumn() {
    return column_ != null;
  }
  /**
   * <pre>
   * the source column name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>.gpss.IntermediateColumn column = 1;</code>
   * @return The column.
   */
  @java.lang.Override
  public gpss.IntermediateColumn getColumn() {
    return column_ == null ? gpss.IntermediateColumn.getDefaultInstance() : column_;
  }
  /**
   * <pre>
   * the source column name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>.gpss.IntermediateColumn column = 1;</code>
   */
  @java.lang.Override
  public gpss.IntermediateColumnOrBuilder getColumnOrBuilder() {
    return getColumn();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (column_ != null) {
      output.writeMessage(1, getColumn());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (column_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getColumn());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.FormatJSON)) {
      return super.equals(obj);
    }
    gpss.FormatJSON other = (gpss.FormatJSON) obj;

    if (hasColumn() != other.hasColumn()) return false;
    if (hasColumn()) {
      if (!getColumn()
          .equals(other.getColumn())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasColumn()) {
      hash = (37 * hash) + COLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getColumn().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.FormatJSON parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.FormatJSON parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.FormatJSON parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.FormatJSON parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.FormatJSON parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.FormatJSON parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.FormatJSON parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.FormatJSON parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.FormatJSON parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.FormatJSON parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.FormatJSON parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.FormatJSON parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.FormatJSON prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gpss.FormatJSON}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.FormatJSON)
      gpss.FormatJSONOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_FormatJSON_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_FormatJSON_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.FormatJSON.class, gpss.FormatJSON.Builder.class);
    }

    // Construct using gpss.FormatJSON.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (columnBuilder_ == null) {
        column_ = null;
      } else {
        column_ = null;
        columnBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_FormatJSON_descriptor;
    }

    @java.lang.Override
    public gpss.FormatJSON getDefaultInstanceForType() {
      return gpss.FormatJSON.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.FormatJSON build() {
      gpss.FormatJSON result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.FormatJSON buildPartial() {
      gpss.FormatJSON result = new gpss.FormatJSON(this);
      if (columnBuilder_ == null) {
        result.column_ = column_;
      } else {
        result.column_ = columnBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.FormatJSON) {
        return mergeFrom((gpss.FormatJSON)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.FormatJSON other) {
      if (other == gpss.FormatJSON.getDefaultInstance()) return this;
      if (other.hasColumn()) {
        mergeColumn(other.getColumn());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.FormatJSON parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.FormatJSON) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private gpss.IntermediateColumn column_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.IntermediateColumn, gpss.IntermediateColumn.Builder, gpss.IntermediateColumnOrBuilder> columnBuilder_;
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     * @return Whether the column field is set.
     */
    public boolean hasColumn() {
      return columnBuilder_ != null || column_ != null;
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     * @return The column.
     */
    public gpss.IntermediateColumn getColumn() {
      if (columnBuilder_ == null) {
        return column_ == null ? gpss.IntermediateColumn.getDefaultInstance() : column_;
      } else {
        return columnBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     */
    public Builder setColumn(gpss.IntermediateColumn value) {
      if (columnBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        column_ = value;
        onChanged();
      } else {
        columnBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     */
    public Builder setColumn(
        gpss.IntermediateColumn.Builder builderForValue) {
      if (columnBuilder_ == null) {
        column_ = builderForValue.build();
        onChanged();
      } else {
        columnBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     */
    public Builder mergeColumn(gpss.IntermediateColumn value) {
      if (columnBuilder_ == null) {
        if (column_ != null) {
          column_ =
            gpss.IntermediateColumn.newBuilder(column_).mergeFrom(value).buildPartial();
        } else {
          column_ = value;
        }
        onChanged();
      } else {
        columnBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     */
    public Builder clearColumn() {
      if (columnBuilder_ == null) {
        column_ = null;
        onChanged();
      } else {
        column_ = null;
        columnBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     */
    public gpss.IntermediateColumn.Builder getColumnBuilder() {
      
      onChanged();
      return getColumnFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     */
    public gpss.IntermediateColumnOrBuilder getColumnOrBuilder() {
      if (columnBuilder_ != null) {
        return columnBuilder_.getMessageOrBuilder();
      } else {
        return column_ == null ?
            gpss.IntermediateColumn.getDefaultInstance() : column_;
      }
    }
    /**
     * <pre>
     * the source column name , may be used in Expression/Mapping node.
     * </pre>
     *
     * <code>.gpss.IntermediateColumn column = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.IntermediateColumn, gpss.IntermediateColumn.Builder, gpss.IntermediateColumnOrBuilder> 
        getColumnFieldBuilder() {
      if (columnBuilder_ == null) {
        columnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.IntermediateColumn, gpss.IntermediateColumn.Builder, gpss.IntermediateColumnOrBuilder>(
                getColumn(),
                getParentForChildren(),
                isClean());
        column_ = null;
      }
      return columnBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.FormatJSON)
  }

  // @@protoc_insertion_point(class_scope:gpss.FormatJSON)
  private static final gpss.FormatJSON DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.FormatJSON();
  }

  public static gpss.FormatJSON getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FormatJSON>
      PARSER = new com.google.protobuf.AbstractParser<FormatJSON>() {
    @java.lang.Override
    public FormatJSON parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FormatJSON(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FormatJSON> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FormatJSON> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.FormatJSON getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

