// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface FormatJSONOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.FormatJSON)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the source column name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>.gpss.IntermediateColumn column = 1;</code>
   * @return Whether the column field is set.
   */
  boolean hasColumn();
  /**
   * <pre>
   * the source column name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>.gpss.IntermediateColumn column = 1;</code>
   * @return The column.
   */
  gpss.IntermediateColumn getColumn();
  /**
   * <pre>
   * the source column name , may be used in Expression/Mapping node.
   * </pre>
   *
   * <code>.gpss.IntermediateColumn column = 1;</code>
   */
  gpss.IntermediateColumnOrBuilder getColumnOrBuilder();
}
