// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface GetCurrentProgressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.GetCurrentProgressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .gpss.JobProgressRecord partition_records = 1;</code>
   */
  java.util.List<gpss.JobProgressRecord> 
      getPartitionRecordsList();
  /**
   * <code>repeated .gpss.JobProgressRecord partition_records = 1;</code>
   */
  gpss.JobProgressRecord getPartitionRecords(int index);
  /**
   * <code>repeated .gpss.JobProgressRecord partition_records = 1;</code>
   */
  int getPartitionRecordsCount();
  /**
   * <code>repeated .gpss.JobProgressRecord partition_records = 1;</code>
   */
  java.util.List<? extends gpss.JobProgressRecordOrBuilder> 
      getPartitionRecordsOrBuilderList();
  /**
   * <code>repeated .gpss.JobProgressRecord partition_records = 1;</code>
   */
  gpss.JobProgressRecordOrBuilder getPartitionRecordsOrBuilder(
      int index);

  /**
   * <code>int64 inserted_record_num = 2;</code>
   * @return The insertedRecordNum.
   */
  long getInsertedRecordNum();

  /**
   * <code>int64 rejected_record_num = 3;</code>
   * @return The rejectedRecordNum.
   */
  long getRejectedRecordNum();
}
