// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface GetJobStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.GetJobStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gpss.JobIdentifier job_identifier = 1;</code>
   * @return Whether the jobIdentifier field is set.
   */
  boolean hasJobIdentifier();
  /**
   * <code>.gpss.JobIdentifier job_identifier = 1;</code>
   * @return The jobIdentifier.
   */
  gpss.JobIdentifier getJobIdentifier();
  /**
   * <code>.gpss.JobIdentifier job_identifier = 1;</code>
   */
  gpss.JobIdentifierOrBuilder getJobIdentifierOrBuilder();
}
