// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * <pre>
 * identify a job by id or name
 * </pre>
 *
 * Protobuf type {@code gpss.JobIdentifier}
 */
public final class JobIdentifier extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.JobIdentifier)
    JobIdentifierOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobIdentifier.newBuilder() to construct.
  private JobIdentifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobIdentifier() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobIdentifier();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobIdentifier(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            unitCase_ = 1;
            unit_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            unitCase_ = 2;
            unit_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_JobIdentifier_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_JobIdentifier_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.JobIdentifier.class, gpss.JobIdentifier.Builder.class);
  }

  private int unitCase_ = 0;
  private java.lang.Object unit_;
  public enum UnitCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    JOB_ID(1),
    JOB_NAME(2),
    UNIT_NOT_SET(0);
    private final int value;
    private UnitCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UnitCase valueOf(int value) {
      return forNumber(value);
    }

    public static UnitCase forNumber(int value) {
      switch (value) {
        case 1: return JOB_ID;
        case 2: return JOB_NAME;
        case 0: return UNIT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public UnitCase
  getUnitCase() {
    return UnitCase.forNumber(
        unitCase_);
  }

  public static final int JOB_ID_FIELD_NUMBER = 1;
  /**
   * <pre>
   * unique hash id
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The jobId.
   */
  public java.lang.String getJobId() {
    java.lang.Object ref = "";
    if (unitCase_ == 1) {
      ref = unit_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (unitCase_ == 1) {
        unit_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * unique hash id
   * </pre>
   *
   * <code>string job_id = 1;</code>
   * @return The bytes for jobId.
   */
  public com.google.protobuf.ByteString
      getJobIdBytes() {
    java.lang.Object ref = "";
    if (unitCase_ == 1) {
      ref = unit_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (unitCase_ == 1) {
        unit_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_NAME_FIELD_NUMBER = 2;
  /**
   * <pre>
   * unique job name, map[name][job_uid], TODO rpc
   * </pre>
   *
   * <code>string job_name = 2;</code>
   * @return The jobName.
   */
  public java.lang.String getJobName() {
    java.lang.Object ref = "";
    if (unitCase_ == 2) {
      ref = unit_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (unitCase_ == 2) {
        unit_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * unique job name, map[name][job_uid], TODO rpc
   * </pre>
   *
   * <code>string job_name = 2;</code>
   * @return The bytes for jobName.
   */
  public com.google.protobuf.ByteString
      getJobNameBytes() {
    java.lang.Object ref = "";
    if (unitCase_ == 2) {
      ref = unit_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (unitCase_ == 2) {
        unit_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (unitCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, unit_);
    }
    if (unitCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, unit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unitCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, unit_);
    }
    if (unitCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, unit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.JobIdentifier)) {
      return super.equals(obj);
    }
    gpss.JobIdentifier other = (gpss.JobIdentifier) obj;

    if (!getUnitCase().equals(other.getUnitCase())) return false;
    switch (unitCase_) {
      case 1:
        if (!getJobId()
            .equals(other.getJobId())) return false;
        break;
      case 2:
        if (!getJobName()
            .equals(other.getJobName())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (unitCase_) {
      case 1:
        hash = (37 * hash) + JOB_ID_FIELD_NUMBER;
        hash = (53 * hash) + getJobId().hashCode();
        break;
      case 2:
        hash = (37 * hash) + JOB_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getJobName().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.JobIdentifier parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.JobIdentifier parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.JobIdentifier parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.JobIdentifier parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.JobIdentifier parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.JobIdentifier parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.JobIdentifier parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.JobIdentifier parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.JobIdentifier parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.JobIdentifier parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.JobIdentifier parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.JobIdentifier parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.JobIdentifier prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * identify a job by id or name
   * </pre>
   *
   * Protobuf type {@code gpss.JobIdentifier}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.JobIdentifier)
      gpss.JobIdentifierOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_JobIdentifier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_JobIdentifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.JobIdentifier.class, gpss.JobIdentifier.Builder.class);
    }

    // Construct using gpss.JobIdentifier.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      unitCase_ = 0;
      unit_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_JobIdentifier_descriptor;
    }

    @java.lang.Override
    public gpss.JobIdentifier getDefaultInstanceForType() {
      return gpss.JobIdentifier.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.JobIdentifier build() {
      gpss.JobIdentifier result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.JobIdentifier buildPartial() {
      gpss.JobIdentifier result = new gpss.JobIdentifier(this);
      if (unitCase_ == 1) {
        result.unit_ = unit_;
      }
      if (unitCase_ == 2) {
        result.unit_ = unit_;
      }
      result.unitCase_ = unitCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.JobIdentifier) {
        return mergeFrom((gpss.JobIdentifier)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.JobIdentifier other) {
      if (other == gpss.JobIdentifier.getDefaultInstance()) return this;
      switch (other.getUnitCase()) {
        case JOB_ID: {
          unitCase_ = 1;
          unit_ = other.unit_;
          onChanged();
          break;
        }
        case JOB_NAME: {
          unitCase_ = 2;
          unit_ = other.unit_;
          onChanged();
          break;
        }
        case UNIT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.JobIdentifier parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.JobIdentifier) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int unitCase_ = 0;
    private java.lang.Object unit_;
    public UnitCase
        getUnitCase() {
      return UnitCase.forNumber(
          unitCase_);
    }

    public Builder clearUnit() {
      unitCase_ = 0;
      unit_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     * unique hash id
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @return The jobId.
     */
    @java.lang.Override
    public java.lang.String getJobId() {
      java.lang.Object ref = "";
      if (unitCase_ == 1) {
        ref = unit_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (unitCase_ == 1) {
          unit_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique hash id
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @return The bytes for jobId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = "";
      if (unitCase_ == 1) {
        ref = unit_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (unitCase_ == 1) {
          unit_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique hash id
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @param value The jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  unitCase_ = 1;
      unit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique hash id
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobId() {
      if (unitCase_ == 1) {
        unitCase_ = 0;
        unit_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * unique hash id
     * </pre>
     *
     * <code>string job_id = 1;</code>
     * @param value The bytes for jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      unitCase_ = 1;
      unit_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * unique job name, map[name][job_uid], TODO rpc
     * </pre>
     *
     * <code>string job_name = 2;</code>
     * @return The jobName.
     */
    @java.lang.Override
    public java.lang.String getJobName() {
      java.lang.Object ref = "";
      if (unitCase_ == 2) {
        ref = unit_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (unitCase_ == 2) {
          unit_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique job name, map[name][job_uid], TODO rpc
     * </pre>
     *
     * <code>string job_name = 2;</code>
     * @return The bytes for jobName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJobNameBytes() {
      java.lang.Object ref = "";
      if (unitCase_ == 2) {
        ref = unit_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (unitCase_ == 2) {
          unit_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique job name, map[name][job_uid], TODO rpc
     * </pre>
     *
     * <code>string job_name = 2;</code>
     * @param value The jobName to set.
     * @return This builder for chaining.
     */
    public Builder setJobName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  unitCase_ = 2;
      unit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique job name, map[name][job_uid], TODO rpc
     * </pre>
     *
     * <code>string job_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobName() {
      if (unitCase_ == 2) {
        unitCase_ = 0;
        unit_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * unique job name, map[name][job_uid], TODO rpc
     * </pre>
     *
     * <code>string job_name = 2;</code>
     * @param value The bytes for jobName to set.
     * @return This builder for chaining.
     */
    public Builder setJobNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      unitCase_ = 2;
      unit_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.JobIdentifier)
  }

  // @@protoc_insertion_point(class_scope:gpss.JobIdentifier)
  private static final gpss.JobIdentifier DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.JobIdentifier();
  }

  public static gpss.JobIdentifier getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobIdentifier>
      PARSER = new com.google.protobuf.AbstractParser<JobIdentifier>() {
    @java.lang.Override
    public JobIdentifier parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobIdentifier(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobIdentifier> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobIdentifier> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.JobIdentifier getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

