// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface JobOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.JobOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.gpss.Schedule schedule = 2;</code>
   * @return Whether the schedule field is set.
   */
  boolean hasSchedule();
  /**
   * <code>.gpss.Schedule schedule = 2;</code>
   * @return The schedule.
   */
  gpss.Schedule getSchedule();
  /**
   * <code>.gpss.Schedule schedule = 2;</code>
   */
  gpss.ScheduleOrBuilder getScheduleOrBuilder();
}
