// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * Protobuf type {@code gpss.KafkaSourceExtraOption}
 */
public final class KafkaSourceExtraOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.KafkaSourceExtraOption)
    KafkaSourceExtraOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KafkaSourceExtraOption.newBuilder() to construct.
  private KafkaSourceExtraOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KafkaSourceExtraOption() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KafkaSourceExtraOption();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KafkaSourceExtraOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            quitAtEof_ = input.readBool();
            break;
          }
          case 18: {
            gpss.KafkaReset.Builder subBuilder = null;
            if (kafkaReset_ != null) {
              subBuilder = kafkaReset_.toBuilder();
            }
            kafkaReset_ = input.readMessage(gpss.KafkaReset.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kafkaReset_);
              kafkaReset_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_KafkaSourceExtraOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_KafkaSourceExtraOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.KafkaSourceExtraOption.class, gpss.KafkaSourceExtraOption.Builder.class);
  }

  public static final int QUIT_AT_EOF_FIELD_NUMBER = 1;
  private boolean quitAtEof_;
  /**
   * <pre>
   * specific for rdkafka, if there is no more data, an eof will return and the job will end.
   * </pre>
   *
   * <code>bool quit_at_eof = 1;</code>
   * @return The quitAtEof.
   */
  @java.lang.Override
  public boolean getQuitAtEof() {
    return quitAtEof_;
  }

  public static final int KAFKA_RESET_FIELD_NUMBER = 2;
  private gpss.KafkaReset kafkaReset_;
  /**
   * <pre>
   * reset option
   * </pre>
   *
   * <code>.gpss.KafkaReset kafka_reset = 2;</code>
   * @return Whether the kafkaReset field is set.
   */
  @java.lang.Override
  public boolean hasKafkaReset() {
    return kafkaReset_ != null;
  }
  /**
   * <pre>
   * reset option
   * </pre>
   *
   * <code>.gpss.KafkaReset kafka_reset = 2;</code>
   * @return The kafkaReset.
   */
  @java.lang.Override
  public gpss.KafkaReset getKafkaReset() {
    return kafkaReset_ == null ? gpss.KafkaReset.getDefaultInstance() : kafkaReset_;
  }
  /**
   * <pre>
   * reset option
   * </pre>
   *
   * <code>.gpss.KafkaReset kafka_reset = 2;</code>
   */
  @java.lang.Override
  public gpss.KafkaResetOrBuilder getKafkaResetOrBuilder() {
    return getKafkaReset();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (quitAtEof_ != false) {
      output.writeBool(1, quitAtEof_);
    }
    if (kafkaReset_ != null) {
      output.writeMessage(2, getKafkaReset());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (quitAtEof_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, quitAtEof_);
    }
    if (kafkaReset_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getKafkaReset());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.KafkaSourceExtraOption)) {
      return super.equals(obj);
    }
    gpss.KafkaSourceExtraOption other = (gpss.KafkaSourceExtraOption) obj;

    if (getQuitAtEof()
        != other.getQuitAtEof()) return false;
    if (hasKafkaReset() != other.hasKafkaReset()) return false;
    if (hasKafkaReset()) {
      if (!getKafkaReset()
          .equals(other.getKafkaReset())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUIT_AT_EOF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getQuitAtEof());
    if (hasKafkaReset()) {
      hash = (37 * hash) + KAFKA_RESET_FIELD_NUMBER;
      hash = (53 * hash) + getKafkaReset().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.KafkaSourceExtraOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.KafkaSourceExtraOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.KafkaSourceExtraOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.KafkaSourceExtraOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.KafkaSourceExtraOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gpss.KafkaSourceExtraOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.KafkaSourceExtraOption)
      gpss.KafkaSourceExtraOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_KafkaSourceExtraOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_KafkaSourceExtraOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.KafkaSourceExtraOption.class, gpss.KafkaSourceExtraOption.Builder.class);
    }

    // Construct using gpss.KafkaSourceExtraOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      quitAtEof_ = false;

      if (kafkaResetBuilder_ == null) {
        kafkaReset_ = null;
      } else {
        kafkaReset_ = null;
        kafkaResetBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_KafkaSourceExtraOption_descriptor;
    }

    @java.lang.Override
    public gpss.KafkaSourceExtraOption getDefaultInstanceForType() {
      return gpss.KafkaSourceExtraOption.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.KafkaSourceExtraOption build() {
      gpss.KafkaSourceExtraOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.KafkaSourceExtraOption buildPartial() {
      gpss.KafkaSourceExtraOption result = new gpss.KafkaSourceExtraOption(this);
      result.quitAtEof_ = quitAtEof_;
      if (kafkaResetBuilder_ == null) {
        result.kafkaReset_ = kafkaReset_;
      } else {
        result.kafkaReset_ = kafkaResetBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.KafkaSourceExtraOption) {
        return mergeFrom((gpss.KafkaSourceExtraOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.KafkaSourceExtraOption other) {
      if (other == gpss.KafkaSourceExtraOption.getDefaultInstance()) return this;
      if (other.getQuitAtEof() != false) {
        setQuitAtEof(other.getQuitAtEof());
      }
      if (other.hasKafkaReset()) {
        mergeKafkaReset(other.getKafkaReset());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.KafkaSourceExtraOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.KafkaSourceExtraOption) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean quitAtEof_ ;
    /**
     * <pre>
     * specific for rdkafka, if there is no more data, an eof will return and the job will end.
     * </pre>
     *
     * <code>bool quit_at_eof = 1;</code>
     * @return The quitAtEof.
     */
    @java.lang.Override
    public boolean getQuitAtEof() {
      return quitAtEof_;
    }
    /**
     * <pre>
     * specific for rdkafka, if there is no more data, an eof will return and the job will end.
     * </pre>
     *
     * <code>bool quit_at_eof = 1;</code>
     * @param value The quitAtEof to set.
     * @return This builder for chaining.
     */
    public Builder setQuitAtEof(boolean value) {
      
      quitAtEof_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * specific for rdkafka, if there is no more data, an eof will return and the job will end.
     * </pre>
     *
     * <code>bool quit_at_eof = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuitAtEof() {
      
      quitAtEof_ = false;
      onChanged();
      return this;
    }

    private gpss.KafkaReset kafkaReset_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.KafkaReset, gpss.KafkaReset.Builder, gpss.KafkaResetOrBuilder> kafkaResetBuilder_;
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     * @return Whether the kafkaReset field is set.
     */
    public boolean hasKafkaReset() {
      return kafkaResetBuilder_ != null || kafkaReset_ != null;
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     * @return The kafkaReset.
     */
    public gpss.KafkaReset getKafkaReset() {
      if (kafkaResetBuilder_ == null) {
        return kafkaReset_ == null ? gpss.KafkaReset.getDefaultInstance() : kafkaReset_;
      } else {
        return kafkaResetBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     */
    public Builder setKafkaReset(gpss.KafkaReset value) {
      if (kafkaResetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kafkaReset_ = value;
        onChanged();
      } else {
        kafkaResetBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     */
    public Builder setKafkaReset(
        gpss.KafkaReset.Builder builderForValue) {
      if (kafkaResetBuilder_ == null) {
        kafkaReset_ = builderForValue.build();
        onChanged();
      } else {
        kafkaResetBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     */
    public Builder mergeKafkaReset(gpss.KafkaReset value) {
      if (kafkaResetBuilder_ == null) {
        if (kafkaReset_ != null) {
          kafkaReset_ =
            gpss.KafkaReset.newBuilder(kafkaReset_).mergeFrom(value).buildPartial();
        } else {
          kafkaReset_ = value;
        }
        onChanged();
      } else {
        kafkaResetBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     */
    public Builder clearKafkaReset() {
      if (kafkaResetBuilder_ == null) {
        kafkaReset_ = null;
        onChanged();
      } else {
        kafkaReset_ = null;
        kafkaResetBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     */
    public gpss.KafkaReset.Builder getKafkaResetBuilder() {
      
      onChanged();
      return getKafkaResetFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     */
    public gpss.KafkaResetOrBuilder getKafkaResetOrBuilder() {
      if (kafkaResetBuilder_ != null) {
        return kafkaResetBuilder_.getMessageOrBuilder();
      } else {
        return kafkaReset_ == null ?
            gpss.KafkaReset.getDefaultInstance() : kafkaReset_;
      }
    }
    /**
     * <pre>
     * reset option
     * </pre>
     *
     * <code>.gpss.KafkaReset kafka_reset = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.KafkaReset, gpss.KafkaReset.Builder, gpss.KafkaResetOrBuilder> 
        getKafkaResetFieldBuilder() {
      if (kafkaResetBuilder_ == null) {
        kafkaResetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.KafkaReset, gpss.KafkaReset.Builder, gpss.KafkaResetOrBuilder>(
                getKafkaReset(),
                getParentForChildren(),
                isClean());
        kafkaReset_ = null;
      }
      return kafkaResetBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.KafkaSourceExtraOption)
  }

  // @@protoc_insertion_point(class_scope:gpss.KafkaSourceExtraOption)
  private static final gpss.KafkaSourceExtraOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.KafkaSourceExtraOption();
  }

  public static gpss.KafkaSourceExtraOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KafkaSourceExtraOption>
      PARSER = new com.google.protobuf.AbstractParser<KafkaSourceExtraOption>() {
    @java.lang.Override
    public KafkaSourceExtraOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KafkaSourceExtraOption(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KafkaSourceExtraOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KafkaSourceExtraOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.KafkaSourceExtraOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

