// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * <pre>
 * ListJobs service Response message
 * </pre>
 *
 * Protobuf type {@code gpss.ListJobResponse}
 */
public final class ListJobResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.ListJobResponse)
    ListJobResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListJobResponse.newBuilder() to construct.
  private ListJobResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListJobResponse() {
    jobInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListJobResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListJobResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jobInfos_ = new java.util.ArrayList<gpss.JobInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobInfos_.add(
                input.readMessage(gpss.JobInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jobInfos_ = java.util.Collections.unmodifiableList(jobInfos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_ListJobResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_ListJobResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.ListJobResponse.class, gpss.ListJobResponse.Builder.class);
  }

  public static final int JOB_INFOS_FIELD_NUMBER = 1;
  private java.util.List<gpss.JobInfo> jobInfos_;
  /**
   * <code>repeated .gpss.JobInfo job_infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<gpss.JobInfo> getJobInfosList() {
    return jobInfos_;
  }
  /**
   * <code>repeated .gpss.JobInfo job_infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends gpss.JobInfoOrBuilder> 
      getJobInfosOrBuilderList() {
    return jobInfos_;
  }
  /**
   * <code>repeated .gpss.JobInfo job_infos = 1;</code>
   */
  @java.lang.Override
  public int getJobInfosCount() {
    return jobInfos_.size();
  }
  /**
   * <code>repeated .gpss.JobInfo job_infos = 1;</code>
   */
  @java.lang.Override
  public gpss.JobInfo getJobInfos(int index) {
    return jobInfos_.get(index);
  }
  /**
   * <code>repeated .gpss.JobInfo job_infos = 1;</code>
   */
  @java.lang.Override
  public gpss.JobInfoOrBuilder getJobInfosOrBuilder(
      int index) {
    return jobInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobInfos_.size(); i++) {
      output.writeMessage(1, jobInfos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobInfos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.ListJobResponse)) {
      return super.equals(obj);
    }
    gpss.ListJobResponse other = (gpss.ListJobResponse) obj;

    if (!getJobInfosList()
        .equals(other.getJobInfosList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobInfosCount() > 0) {
      hash = (37 * hash) + JOB_INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getJobInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.ListJobResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.ListJobResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.ListJobResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.ListJobResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.ListJobResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.ListJobResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.ListJobResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.ListJobResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.ListJobResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.ListJobResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.ListJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.ListJobResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.ListJobResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ListJobs service Response message
   * </pre>
   *
   * Protobuf type {@code gpss.ListJobResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.ListJobResponse)
      gpss.ListJobResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_ListJobResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_ListJobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.ListJobResponse.class, gpss.ListJobResponse.Builder.class);
    }

    // Construct using gpss.ListJobResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobInfosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobInfosBuilder_ == null) {
        jobInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobInfosBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_ListJobResponse_descriptor;
    }

    @java.lang.Override
    public gpss.ListJobResponse getDefaultInstanceForType() {
      return gpss.ListJobResponse.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.ListJobResponse build() {
      gpss.ListJobResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.ListJobResponse buildPartial() {
      gpss.ListJobResponse result = new gpss.ListJobResponse(this);
      int from_bitField0_ = bitField0_;
      if (jobInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobInfos_ = java.util.Collections.unmodifiableList(jobInfos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobInfos_ = jobInfos_;
      } else {
        result.jobInfos_ = jobInfosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.ListJobResponse) {
        return mergeFrom((gpss.ListJobResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.ListJobResponse other) {
      if (other == gpss.ListJobResponse.getDefaultInstance()) return this;
      if (jobInfosBuilder_ == null) {
        if (!other.jobInfos_.isEmpty()) {
          if (jobInfos_.isEmpty()) {
            jobInfos_ = other.jobInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobInfosIsMutable();
            jobInfos_.addAll(other.jobInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.jobInfos_.isEmpty()) {
          if (jobInfosBuilder_.isEmpty()) {
            jobInfosBuilder_.dispose();
            jobInfosBuilder_ = null;
            jobInfos_ = other.jobInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobInfosFieldBuilder() : null;
          } else {
            jobInfosBuilder_.addAllMessages(other.jobInfos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.ListJobResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.ListJobResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<gpss.JobInfo> jobInfos_ =
      java.util.Collections.emptyList();
    private void ensureJobInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobInfos_ = new java.util.ArrayList<gpss.JobInfo>(jobInfos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        gpss.JobInfo, gpss.JobInfo.Builder, gpss.JobInfoOrBuilder> jobInfosBuilder_;

    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public java.util.List<gpss.JobInfo> getJobInfosList() {
      if (jobInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobInfos_);
      } else {
        return jobInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public int getJobInfosCount() {
      if (jobInfosBuilder_ == null) {
        return jobInfos_.size();
      } else {
        return jobInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public gpss.JobInfo getJobInfos(int index) {
      if (jobInfosBuilder_ == null) {
        return jobInfos_.get(index);
      } else {
        return jobInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder setJobInfos(
        int index, gpss.JobInfo value) {
      if (jobInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobInfosIsMutable();
        jobInfos_.set(index, value);
        onChanged();
      } else {
        jobInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder setJobInfos(
        int index, gpss.JobInfo.Builder builderForValue) {
      if (jobInfosBuilder_ == null) {
        ensureJobInfosIsMutable();
        jobInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder addJobInfos(gpss.JobInfo value) {
      if (jobInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobInfosIsMutable();
        jobInfos_.add(value);
        onChanged();
      } else {
        jobInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder addJobInfos(
        int index, gpss.JobInfo value) {
      if (jobInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobInfosIsMutable();
        jobInfos_.add(index, value);
        onChanged();
      } else {
        jobInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder addJobInfos(
        gpss.JobInfo.Builder builderForValue) {
      if (jobInfosBuilder_ == null) {
        ensureJobInfosIsMutable();
        jobInfos_.add(builderForValue.build());
        onChanged();
      } else {
        jobInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder addJobInfos(
        int index, gpss.JobInfo.Builder builderForValue) {
      if (jobInfosBuilder_ == null) {
        ensureJobInfosIsMutable();
        jobInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder addAllJobInfos(
        java.lang.Iterable<? extends gpss.JobInfo> values) {
      if (jobInfosBuilder_ == null) {
        ensureJobInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobInfos_);
        onChanged();
      } else {
        jobInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder clearJobInfos() {
      if (jobInfosBuilder_ == null) {
        jobInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public Builder removeJobInfos(int index) {
      if (jobInfosBuilder_ == null) {
        ensureJobInfosIsMutable();
        jobInfos_.remove(index);
        onChanged();
      } else {
        jobInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public gpss.JobInfo.Builder getJobInfosBuilder(
        int index) {
      return getJobInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public gpss.JobInfoOrBuilder getJobInfosOrBuilder(
        int index) {
      if (jobInfosBuilder_ == null) {
        return jobInfos_.get(index);  } else {
        return jobInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public java.util.List<? extends gpss.JobInfoOrBuilder> 
         getJobInfosOrBuilderList() {
      if (jobInfosBuilder_ != null) {
        return jobInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobInfos_);
      }
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public gpss.JobInfo.Builder addJobInfosBuilder() {
      return getJobInfosFieldBuilder().addBuilder(
          gpss.JobInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public gpss.JobInfo.Builder addJobInfosBuilder(
        int index) {
      return getJobInfosFieldBuilder().addBuilder(
          index, gpss.JobInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .gpss.JobInfo job_infos = 1;</code>
     */
    public java.util.List<gpss.JobInfo.Builder> 
         getJobInfosBuilderList() {
      return getJobInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        gpss.JobInfo, gpss.JobInfo.Builder, gpss.JobInfoOrBuilder> 
        getJobInfosFieldBuilder() {
      if (jobInfosBuilder_ == null) {
        jobInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            gpss.JobInfo, gpss.JobInfo.Builder, gpss.JobInfoOrBuilder>(
                jobInfos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobInfos_ = null;
      }
      return jobInfosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.ListJobResponse)
  }

  // @@protoc_insertion_point(class_scope:gpss.ListJobResponse)
  private static final gpss.ListJobResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.ListJobResponse();
  }

  public static gpss.ListJobResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListJobResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListJobResponse>() {
    @java.lang.Override
    public ListJobResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListJobResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListJobResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListJobResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.ListJobResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

