// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * Protobuf type {@code gpss.Mode}
 */
public final class Mode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.Mode)
    ModeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Mode.newBuilder() to construct.
  private Mode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Mode() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Mode();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Mode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            gpss.InsertMode.Builder subBuilder = null;
            if (unitCase_ == 1) {
              subBuilder = ((gpss.InsertMode) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.InsertMode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.InsertMode) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 1;
            break;
          }
          case 18: {
            gpss.UpdateMode.Builder subBuilder = null;
            if (unitCase_ == 2) {
              subBuilder = ((gpss.UpdateMode) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.UpdateMode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.UpdateMode) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 2;
            break;
          }
          case 26: {
            gpss.MergeMode.Builder subBuilder = null;
            if (unitCase_ == 3) {
              subBuilder = ((gpss.MergeMode) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.MergeMode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.MergeMode) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_Mode_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_Mode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.Mode.class, gpss.Mode.Builder.class);
  }

  private int unitCase_ = 0;
  private java.lang.Object unit_;
  public enum UnitCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INSERT(1),
    UPDATE(2),
    MERGE(3),
    UNIT_NOT_SET(0);
    private final int value;
    private UnitCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UnitCase valueOf(int value) {
      return forNumber(value);
    }

    public static UnitCase forNumber(int value) {
      switch (value) {
        case 1: return INSERT;
        case 2: return UPDATE;
        case 3: return MERGE;
        case 0: return UNIT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public UnitCase
  getUnitCase() {
    return UnitCase.forNumber(
        unitCase_);
  }

  public static final int INSERT_FIELD_NUMBER = 1;
  /**
   * <code>.gpss.InsertMode insert = 1;</code>
   * @return Whether the insert field is set.
   */
  @java.lang.Override
  public boolean hasInsert() {
    return unitCase_ == 1;
  }
  /**
   * <code>.gpss.InsertMode insert = 1;</code>
   * @return The insert.
   */
  @java.lang.Override
  public gpss.InsertMode getInsert() {
    if (unitCase_ == 1) {
       return (gpss.InsertMode) unit_;
    }
    return gpss.InsertMode.getDefaultInstance();
  }
  /**
   * <code>.gpss.InsertMode insert = 1;</code>
   */
  @java.lang.Override
  public gpss.InsertModeOrBuilder getInsertOrBuilder() {
    if (unitCase_ == 1) {
       return (gpss.InsertMode) unit_;
    }
    return gpss.InsertMode.getDefaultInstance();
  }

  public static final int UPDATE_FIELD_NUMBER = 2;
  /**
   * <code>.gpss.UpdateMode update = 2;</code>
   * @return Whether the update field is set.
   */
  @java.lang.Override
  public boolean hasUpdate() {
    return unitCase_ == 2;
  }
  /**
   * <code>.gpss.UpdateMode update = 2;</code>
   * @return The update.
   */
  @java.lang.Override
  public gpss.UpdateMode getUpdate() {
    if (unitCase_ == 2) {
       return (gpss.UpdateMode) unit_;
    }
    return gpss.UpdateMode.getDefaultInstance();
  }
  /**
   * <code>.gpss.UpdateMode update = 2;</code>
   */
  @java.lang.Override
  public gpss.UpdateModeOrBuilder getUpdateOrBuilder() {
    if (unitCase_ == 2) {
       return (gpss.UpdateMode) unit_;
    }
    return gpss.UpdateMode.getDefaultInstance();
  }

  public static final int MERGE_FIELD_NUMBER = 3;
  /**
   * <code>.gpss.MergeMode merge = 3;</code>
   * @return Whether the merge field is set.
   */
  @java.lang.Override
  public boolean hasMerge() {
    return unitCase_ == 3;
  }
  /**
   * <code>.gpss.MergeMode merge = 3;</code>
   * @return The merge.
   */
  @java.lang.Override
  public gpss.MergeMode getMerge() {
    if (unitCase_ == 3) {
       return (gpss.MergeMode) unit_;
    }
    return gpss.MergeMode.getDefaultInstance();
  }
  /**
   * <code>.gpss.MergeMode merge = 3;</code>
   */
  @java.lang.Override
  public gpss.MergeModeOrBuilder getMergeOrBuilder() {
    if (unitCase_ == 3) {
       return (gpss.MergeMode) unit_;
    }
    return gpss.MergeMode.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (unitCase_ == 1) {
      output.writeMessage(1, (gpss.InsertMode) unit_);
    }
    if (unitCase_ == 2) {
      output.writeMessage(2, (gpss.UpdateMode) unit_);
    }
    if (unitCase_ == 3) {
      output.writeMessage(3, (gpss.MergeMode) unit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unitCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (gpss.InsertMode) unit_);
    }
    if (unitCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (gpss.UpdateMode) unit_);
    }
    if (unitCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (gpss.MergeMode) unit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.Mode)) {
      return super.equals(obj);
    }
    gpss.Mode other = (gpss.Mode) obj;

    if (!getUnitCase().equals(other.getUnitCase())) return false;
    switch (unitCase_) {
      case 1:
        if (!getInsert()
            .equals(other.getInsert())) return false;
        break;
      case 2:
        if (!getUpdate()
            .equals(other.getUpdate())) return false;
        break;
      case 3:
        if (!getMerge()
            .equals(other.getMerge())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (unitCase_) {
      case 1:
        hash = (37 * hash) + INSERT_FIELD_NUMBER;
        hash = (53 * hash) + getInsert().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getUpdate().hashCode();
        break;
      case 3:
        hash = (37 * hash) + MERGE_FIELD_NUMBER;
        hash = (53 * hash) + getMerge().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.Mode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.Mode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.Mode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.Mode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.Mode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.Mode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.Mode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.Mode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.Mode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.Mode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.Mode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.Mode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.Mode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gpss.Mode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.Mode)
      gpss.ModeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_Mode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_Mode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.Mode.class, gpss.Mode.Builder.class);
    }

    // Construct using gpss.Mode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      unitCase_ = 0;
      unit_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_Mode_descriptor;
    }

    @java.lang.Override
    public gpss.Mode getDefaultInstanceForType() {
      return gpss.Mode.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.Mode build() {
      gpss.Mode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.Mode buildPartial() {
      gpss.Mode result = new gpss.Mode(this);
      if (unitCase_ == 1) {
        if (insertBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = insertBuilder_.build();
        }
      }
      if (unitCase_ == 2) {
        if (updateBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = updateBuilder_.build();
        }
      }
      if (unitCase_ == 3) {
        if (mergeBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = mergeBuilder_.build();
        }
      }
      result.unitCase_ = unitCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.Mode) {
        return mergeFrom((gpss.Mode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.Mode other) {
      if (other == gpss.Mode.getDefaultInstance()) return this;
      switch (other.getUnitCase()) {
        case INSERT: {
          mergeInsert(other.getInsert());
          break;
        }
        case UPDATE: {
          mergeUpdate(other.getUpdate());
          break;
        }
        case MERGE: {
          mergeMerge(other.getMerge());
          break;
        }
        case UNIT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.Mode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.Mode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int unitCase_ = 0;
    private java.lang.Object unit_;
    public UnitCase
        getUnitCase() {
      return UnitCase.forNumber(
          unitCase_);
    }

    public Builder clearUnit() {
      unitCase_ = 0;
      unit_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.InsertMode, gpss.InsertMode.Builder, gpss.InsertModeOrBuilder> insertBuilder_;
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     * @return Whether the insert field is set.
     */
    @java.lang.Override
    public boolean hasInsert() {
      return unitCase_ == 1;
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     * @return The insert.
     */
    @java.lang.Override
    public gpss.InsertMode getInsert() {
      if (insertBuilder_ == null) {
        if (unitCase_ == 1) {
          return (gpss.InsertMode) unit_;
        }
        return gpss.InsertMode.getDefaultInstance();
      } else {
        if (unitCase_ == 1) {
          return insertBuilder_.getMessage();
        }
        return gpss.InsertMode.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     */
    public Builder setInsert(gpss.InsertMode value) {
      if (insertBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        insertBuilder_.setMessage(value);
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     */
    public Builder setInsert(
        gpss.InsertMode.Builder builderForValue) {
      if (insertBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        insertBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     */
    public Builder mergeInsert(gpss.InsertMode value) {
      if (insertBuilder_ == null) {
        if (unitCase_ == 1 &&
            unit_ != gpss.InsertMode.getDefaultInstance()) {
          unit_ = gpss.InsertMode.newBuilder((gpss.InsertMode) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 1) {
          insertBuilder_.mergeFrom(value);
        }
        insertBuilder_.setMessage(value);
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     */
    public Builder clearInsert() {
      if (insertBuilder_ == null) {
        if (unitCase_ == 1) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 1) {
          unitCase_ = 0;
          unit_ = null;
        }
        insertBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     */
    public gpss.InsertMode.Builder getInsertBuilder() {
      return getInsertFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     */
    @java.lang.Override
    public gpss.InsertModeOrBuilder getInsertOrBuilder() {
      if ((unitCase_ == 1) && (insertBuilder_ != null)) {
        return insertBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 1) {
          return (gpss.InsertMode) unit_;
        }
        return gpss.InsertMode.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.InsertMode insert = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.InsertMode, gpss.InsertMode.Builder, gpss.InsertModeOrBuilder> 
        getInsertFieldBuilder() {
      if (insertBuilder_ == null) {
        if (!(unitCase_ == 1)) {
          unit_ = gpss.InsertMode.getDefaultInstance();
        }
        insertBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.InsertMode, gpss.InsertMode.Builder, gpss.InsertModeOrBuilder>(
                (gpss.InsertMode) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 1;
      onChanged();;
      return insertBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.UpdateMode, gpss.UpdateMode.Builder, gpss.UpdateModeOrBuilder> updateBuilder_;
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     * @return Whether the update field is set.
     */
    @java.lang.Override
    public boolean hasUpdate() {
      return unitCase_ == 2;
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     * @return The update.
     */
    @java.lang.Override
    public gpss.UpdateMode getUpdate() {
      if (updateBuilder_ == null) {
        if (unitCase_ == 2) {
          return (gpss.UpdateMode) unit_;
        }
        return gpss.UpdateMode.getDefaultInstance();
      } else {
        if (unitCase_ == 2) {
          return updateBuilder_.getMessage();
        }
        return gpss.UpdateMode.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     */
    public Builder setUpdate(gpss.UpdateMode value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        updateBuilder_.setMessage(value);
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     */
    public Builder setUpdate(
        gpss.UpdateMode.Builder builderForValue) {
      if (updateBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        updateBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     */
    public Builder mergeUpdate(gpss.UpdateMode value) {
      if (updateBuilder_ == null) {
        if (unitCase_ == 2 &&
            unit_ != gpss.UpdateMode.getDefaultInstance()) {
          unit_ = gpss.UpdateMode.newBuilder((gpss.UpdateMode) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 2) {
          updateBuilder_.mergeFrom(value);
        }
        updateBuilder_.setMessage(value);
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     */
    public Builder clearUpdate() {
      if (updateBuilder_ == null) {
        if (unitCase_ == 2) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 2) {
          unitCase_ = 0;
          unit_ = null;
        }
        updateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     */
    public gpss.UpdateMode.Builder getUpdateBuilder() {
      return getUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     */
    @java.lang.Override
    public gpss.UpdateModeOrBuilder getUpdateOrBuilder() {
      if ((unitCase_ == 2) && (updateBuilder_ != null)) {
        return updateBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 2) {
          return (gpss.UpdateMode) unit_;
        }
        return gpss.UpdateMode.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.UpdateMode update = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.UpdateMode, gpss.UpdateMode.Builder, gpss.UpdateModeOrBuilder> 
        getUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        if (!(unitCase_ == 2)) {
          unit_ = gpss.UpdateMode.getDefaultInstance();
        }
        updateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.UpdateMode, gpss.UpdateMode.Builder, gpss.UpdateModeOrBuilder>(
                (gpss.UpdateMode) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 2;
      onChanged();;
      return updateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.MergeMode, gpss.MergeMode.Builder, gpss.MergeModeOrBuilder> mergeBuilder_;
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     * @return Whether the merge field is set.
     */
    @java.lang.Override
    public boolean hasMerge() {
      return unitCase_ == 3;
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     * @return The merge.
     */
    @java.lang.Override
    public gpss.MergeMode getMerge() {
      if (mergeBuilder_ == null) {
        if (unitCase_ == 3) {
          return (gpss.MergeMode) unit_;
        }
        return gpss.MergeMode.getDefaultInstance();
      } else {
        if (unitCase_ == 3) {
          return mergeBuilder_.getMessage();
        }
        return gpss.MergeMode.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     */
    public Builder setMerge(gpss.MergeMode value) {
      if (mergeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        mergeBuilder_.setMessage(value);
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     */
    public Builder setMerge(
        gpss.MergeMode.Builder builderForValue) {
      if (mergeBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        mergeBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     */
    public Builder mergeMerge(gpss.MergeMode value) {
      if (mergeBuilder_ == null) {
        if (unitCase_ == 3 &&
            unit_ != gpss.MergeMode.getDefaultInstance()) {
          unit_ = gpss.MergeMode.newBuilder((gpss.MergeMode) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 3) {
          mergeBuilder_.mergeFrom(value);
        }
        mergeBuilder_.setMessage(value);
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     */
    public Builder clearMerge() {
      if (mergeBuilder_ == null) {
        if (unitCase_ == 3) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 3) {
          unitCase_ = 0;
          unit_ = null;
        }
        mergeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     */
    public gpss.MergeMode.Builder getMergeBuilder() {
      return getMergeFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     */
    @java.lang.Override
    public gpss.MergeModeOrBuilder getMergeOrBuilder() {
      if ((unitCase_ == 3) && (mergeBuilder_ != null)) {
        return mergeBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 3) {
          return (gpss.MergeMode) unit_;
        }
        return gpss.MergeMode.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.MergeMode merge = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.MergeMode, gpss.MergeMode.Builder, gpss.MergeModeOrBuilder> 
        getMergeFieldBuilder() {
      if (mergeBuilder_ == null) {
        if (!(unitCase_ == 3)) {
          unit_ = gpss.MergeMode.getDefaultInstance();
        }
        mergeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.MergeMode, gpss.MergeMode.Builder, gpss.MergeModeOrBuilder>(
                (gpss.MergeMode) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 3;
      onChanged();;
      return mergeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.Mode)
  }

  // @@protoc_insertion_point(class_scope:gpss.Mode)
  private static final gpss.Mode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.Mode();
  }

  public static gpss.Mode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Mode>
      PARSER = new com.google.protobuf.AbstractParser<Mode>() {
    @java.lang.Override
    public Mode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Mode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Mode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Mode> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.Mode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

