// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * Protobuf type {@code gpss.RemoveJobRequest}
 */
public final class RemoveJobRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.RemoveJobRequest)
    RemoveJobRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemoveJobRequest.newBuilder() to construct.
  private RemoveJobRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemoveJobRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RemoveJobRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RemoveJobRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            gpss.JobIdentifier.Builder subBuilder = null;
            if (jobIdentifier_ != null) {
              subBuilder = jobIdentifier_.toBuilder();
            }
            jobIdentifier_ = input.readMessage(gpss.JobIdentifier.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(jobIdentifier_);
              jobIdentifier_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_RemoveJobRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_RemoveJobRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.RemoveJobRequest.class, gpss.RemoveJobRequest.Builder.class);
  }

  public static final int JOB_IDENTIFIER_FIELD_NUMBER = 1;
  private gpss.JobIdentifier jobIdentifier_;
  /**
   * <code>.gpss.JobIdentifier job_identifier = 1;</code>
   * @return Whether the jobIdentifier field is set.
   */
  @java.lang.Override
  public boolean hasJobIdentifier() {
    return jobIdentifier_ != null;
  }
  /**
   * <code>.gpss.JobIdentifier job_identifier = 1;</code>
   * @return The jobIdentifier.
   */
  @java.lang.Override
  public gpss.JobIdentifier getJobIdentifier() {
    return jobIdentifier_ == null ? gpss.JobIdentifier.getDefaultInstance() : jobIdentifier_;
  }
  /**
   * <code>.gpss.JobIdentifier job_identifier = 1;</code>
   */
  @java.lang.Override
  public gpss.JobIdentifierOrBuilder getJobIdentifierOrBuilder() {
    return getJobIdentifier();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (jobIdentifier_ != null) {
      output.writeMessage(1, getJobIdentifier());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (jobIdentifier_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getJobIdentifier());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.RemoveJobRequest)) {
      return super.equals(obj);
    }
    gpss.RemoveJobRequest other = (gpss.RemoveJobRequest) obj;

    if (hasJobIdentifier() != other.hasJobIdentifier()) return false;
    if (hasJobIdentifier()) {
      if (!getJobIdentifier()
          .equals(other.getJobIdentifier())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasJobIdentifier()) {
      hash = (37 * hash) + JOB_IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getJobIdentifier().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.RemoveJobRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.RemoveJobRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.RemoveJobRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.RemoveJobRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.RemoveJobRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.RemoveJobRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.RemoveJobRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.RemoveJobRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.RemoveJobRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.RemoveJobRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.RemoveJobRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.RemoveJobRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.RemoveJobRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gpss.RemoveJobRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.RemoveJobRequest)
      gpss.RemoveJobRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_RemoveJobRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_RemoveJobRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.RemoveJobRequest.class, gpss.RemoveJobRequest.Builder.class);
    }

    // Construct using gpss.RemoveJobRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobIdentifierBuilder_ == null) {
        jobIdentifier_ = null;
      } else {
        jobIdentifier_ = null;
        jobIdentifierBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_RemoveJobRequest_descriptor;
    }

    @java.lang.Override
    public gpss.RemoveJobRequest getDefaultInstanceForType() {
      return gpss.RemoveJobRequest.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.RemoveJobRequest build() {
      gpss.RemoveJobRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.RemoveJobRequest buildPartial() {
      gpss.RemoveJobRequest result = new gpss.RemoveJobRequest(this);
      if (jobIdentifierBuilder_ == null) {
        result.jobIdentifier_ = jobIdentifier_;
      } else {
        result.jobIdentifier_ = jobIdentifierBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.RemoveJobRequest) {
        return mergeFrom((gpss.RemoveJobRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.RemoveJobRequest other) {
      if (other == gpss.RemoveJobRequest.getDefaultInstance()) return this;
      if (other.hasJobIdentifier()) {
        mergeJobIdentifier(other.getJobIdentifier());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.RemoveJobRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.RemoveJobRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private gpss.JobIdentifier jobIdentifier_;
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.JobIdentifier, gpss.JobIdentifier.Builder, gpss.JobIdentifierOrBuilder> jobIdentifierBuilder_;
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     * @return Whether the jobIdentifier field is set.
     */
    public boolean hasJobIdentifier() {
      return jobIdentifierBuilder_ != null || jobIdentifier_ != null;
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     * @return The jobIdentifier.
     */
    public gpss.JobIdentifier getJobIdentifier() {
      if (jobIdentifierBuilder_ == null) {
        return jobIdentifier_ == null ? gpss.JobIdentifier.getDefaultInstance() : jobIdentifier_;
      } else {
        return jobIdentifierBuilder_.getMessage();
      }
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     */
    public Builder setJobIdentifier(gpss.JobIdentifier value) {
      if (jobIdentifierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        jobIdentifier_ = value;
        onChanged();
      } else {
        jobIdentifierBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     */
    public Builder setJobIdentifier(
        gpss.JobIdentifier.Builder builderForValue) {
      if (jobIdentifierBuilder_ == null) {
        jobIdentifier_ = builderForValue.build();
        onChanged();
      } else {
        jobIdentifierBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     */
    public Builder mergeJobIdentifier(gpss.JobIdentifier value) {
      if (jobIdentifierBuilder_ == null) {
        if (jobIdentifier_ != null) {
          jobIdentifier_ =
            gpss.JobIdentifier.newBuilder(jobIdentifier_).mergeFrom(value).buildPartial();
        } else {
          jobIdentifier_ = value;
        }
        onChanged();
      } else {
        jobIdentifierBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     */
    public Builder clearJobIdentifier() {
      if (jobIdentifierBuilder_ == null) {
        jobIdentifier_ = null;
        onChanged();
      } else {
        jobIdentifier_ = null;
        jobIdentifierBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     */
    public gpss.JobIdentifier.Builder getJobIdentifierBuilder() {
      
      onChanged();
      return getJobIdentifierFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     */
    public gpss.JobIdentifierOrBuilder getJobIdentifierOrBuilder() {
      if (jobIdentifierBuilder_ != null) {
        return jobIdentifierBuilder_.getMessageOrBuilder();
      } else {
        return jobIdentifier_ == null ?
            gpss.JobIdentifier.getDefaultInstance() : jobIdentifier_;
      }
    }
    /**
     * <code>.gpss.JobIdentifier job_identifier = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.JobIdentifier, gpss.JobIdentifier.Builder, gpss.JobIdentifierOrBuilder> 
        getJobIdentifierFieldBuilder() {
      if (jobIdentifierBuilder_ == null) {
        jobIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.JobIdentifier, gpss.JobIdentifier.Builder, gpss.JobIdentifierOrBuilder>(
                getJobIdentifier(),
                getParentForChildren(),
                isClean());
        jobIdentifier_ = null;
      }
      return jobIdentifierBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.RemoveJobRequest)
  }

  // @@protoc_insertion_point(class_scope:gpss.RemoveJobRequest)
  private static final gpss.RemoveJobRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.RemoveJobRequest();
  }

  public static gpss.RemoveJobRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoveJobRequest>
      PARSER = new com.google.protobuf.AbstractParser<RemoveJobRequest>() {
    @java.lang.Override
    public RemoveJobRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RemoveJobRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RemoveJobRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoveJobRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.RemoveJobRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

