// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface RemoveJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.RemoveJobResponse)
    com.google.protobuf.MessageOrBuilder {
}
