// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * <pre>
 * source data's format.
 * if there is an intermediate column inside Format,
 * then the source data will be transformed to the intermediate column.
 * If there is no source_column_name in Format,
 * then the column name will be the Target table column name,
 * and the source column data type should be matched with Target column type.
 * </pre>
 *
 * Protobuf type {@code gpss.SourceDataFormat}
 */
public final class SourceDataFormat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.SourceDataFormat)
    SourceDataFormatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SourceDataFormat.newBuilder() to construct.
  private SourceDataFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SourceDataFormat() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SourceDataFormat();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SourceDataFormat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            gpss.FormatAvro.Builder subBuilder = null;
            if (unitCase_ == 1) {
              subBuilder = ((gpss.FormatAvro) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.FormatAvro.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.FormatAvro) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 1;
            break;
          }
          case 18: {
            gpss.FormatBinary.Builder subBuilder = null;
            if (unitCase_ == 2) {
              subBuilder = ((gpss.FormatBinary) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.FormatBinary.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.FormatBinary) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 2;
            break;
          }
          case 26: {
            gpss.FormatCSV.Builder subBuilder = null;
            if (unitCase_ == 3) {
              subBuilder = ((gpss.FormatCSV) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.FormatCSV.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.FormatCSV) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 3;
            break;
          }
          case 34: {
            gpss.FormatDelimited.Builder subBuilder = null;
            if (unitCase_ == 4) {
              subBuilder = ((gpss.FormatDelimited) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.FormatDelimited.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.FormatDelimited) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 4;
            break;
          }
          case 42: {
            gpss.FormatJSON.Builder subBuilder = null;
            if (unitCase_ == 5) {
              subBuilder = ((gpss.FormatJSON) unit_).toBuilder();
            }
            unit_ =
                input.readMessage(gpss.FormatJSON.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((gpss.FormatJSON) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_SourceDataFormat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_SourceDataFormat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.SourceDataFormat.class, gpss.SourceDataFormat.Builder.class);
  }

  private int unitCase_ = 0;
  private java.lang.Object unit_;
  public enum UnitCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    AVRO(1),
    BINARY(2),
    CSV(3),
    DELIMITED(4),
    JSON(5),
    UNIT_NOT_SET(0);
    private final int value;
    private UnitCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UnitCase valueOf(int value) {
      return forNumber(value);
    }

    public static UnitCase forNumber(int value) {
      switch (value) {
        case 1: return AVRO;
        case 2: return BINARY;
        case 3: return CSV;
        case 4: return DELIMITED;
        case 5: return JSON;
        case 0: return UNIT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public UnitCase
  getUnitCase() {
    return UnitCase.forNumber(
        unitCase_);
  }

  public static final int AVRO_FIELD_NUMBER = 1;
  /**
   * <code>.gpss.FormatAvro avro = 1;</code>
   * @return Whether the avro field is set.
   */
  @java.lang.Override
  public boolean hasAvro() {
    return unitCase_ == 1;
  }
  /**
   * <code>.gpss.FormatAvro avro = 1;</code>
   * @return The avro.
   */
  @java.lang.Override
  public gpss.FormatAvro getAvro() {
    if (unitCase_ == 1) {
       return (gpss.FormatAvro) unit_;
    }
    return gpss.FormatAvro.getDefaultInstance();
  }
  /**
   * <code>.gpss.FormatAvro avro = 1;</code>
   */
  @java.lang.Override
  public gpss.FormatAvroOrBuilder getAvroOrBuilder() {
    if (unitCase_ == 1) {
       return (gpss.FormatAvro) unit_;
    }
    return gpss.FormatAvro.getDefaultInstance();
  }

  public static final int BINARY_FIELD_NUMBER = 2;
  /**
   * <code>.gpss.FormatBinary binary = 2;</code>
   * @return Whether the binary field is set.
   */
  @java.lang.Override
  public boolean hasBinary() {
    return unitCase_ == 2;
  }
  /**
   * <code>.gpss.FormatBinary binary = 2;</code>
   * @return The binary.
   */
  @java.lang.Override
  public gpss.FormatBinary getBinary() {
    if (unitCase_ == 2) {
       return (gpss.FormatBinary) unit_;
    }
    return gpss.FormatBinary.getDefaultInstance();
  }
  /**
   * <code>.gpss.FormatBinary binary = 2;</code>
   */
  @java.lang.Override
  public gpss.FormatBinaryOrBuilder getBinaryOrBuilder() {
    if (unitCase_ == 2) {
       return (gpss.FormatBinary) unit_;
    }
    return gpss.FormatBinary.getDefaultInstance();
  }

  public static final int CSV_FIELD_NUMBER = 3;
  /**
   * <code>.gpss.FormatCSV csv = 3;</code>
   * @return Whether the csv field is set.
   */
  @java.lang.Override
  public boolean hasCsv() {
    return unitCase_ == 3;
  }
  /**
   * <code>.gpss.FormatCSV csv = 3;</code>
   * @return The csv.
   */
  @java.lang.Override
  public gpss.FormatCSV getCsv() {
    if (unitCase_ == 3) {
       return (gpss.FormatCSV) unit_;
    }
    return gpss.FormatCSV.getDefaultInstance();
  }
  /**
   * <code>.gpss.FormatCSV csv = 3;</code>
   */
  @java.lang.Override
  public gpss.FormatCSVOrBuilder getCsvOrBuilder() {
    if (unitCase_ == 3) {
       return (gpss.FormatCSV) unit_;
    }
    return gpss.FormatCSV.getDefaultInstance();
  }

  public static final int DELIMITED_FIELD_NUMBER = 4;
  /**
   * <code>.gpss.FormatDelimited delimited = 4;</code>
   * @return Whether the delimited field is set.
   */
  @java.lang.Override
  public boolean hasDelimited() {
    return unitCase_ == 4;
  }
  /**
   * <code>.gpss.FormatDelimited delimited = 4;</code>
   * @return The delimited.
   */
  @java.lang.Override
  public gpss.FormatDelimited getDelimited() {
    if (unitCase_ == 4) {
       return (gpss.FormatDelimited) unit_;
    }
    return gpss.FormatDelimited.getDefaultInstance();
  }
  /**
   * <code>.gpss.FormatDelimited delimited = 4;</code>
   */
  @java.lang.Override
  public gpss.FormatDelimitedOrBuilder getDelimitedOrBuilder() {
    if (unitCase_ == 4) {
       return (gpss.FormatDelimited) unit_;
    }
    return gpss.FormatDelimited.getDefaultInstance();
  }

  public static final int JSON_FIELD_NUMBER = 5;
  /**
   * <code>.gpss.FormatJSON json = 5;</code>
   * @return Whether the json field is set.
   */
  @java.lang.Override
  public boolean hasJson() {
    return unitCase_ == 5;
  }
  /**
   * <code>.gpss.FormatJSON json = 5;</code>
   * @return The json.
   */
  @java.lang.Override
  public gpss.FormatJSON getJson() {
    if (unitCase_ == 5) {
       return (gpss.FormatJSON) unit_;
    }
    return gpss.FormatJSON.getDefaultInstance();
  }
  /**
   * <code>.gpss.FormatJSON json = 5;</code>
   */
  @java.lang.Override
  public gpss.FormatJSONOrBuilder getJsonOrBuilder() {
    if (unitCase_ == 5) {
       return (gpss.FormatJSON) unit_;
    }
    return gpss.FormatJSON.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (unitCase_ == 1) {
      output.writeMessage(1, (gpss.FormatAvro) unit_);
    }
    if (unitCase_ == 2) {
      output.writeMessage(2, (gpss.FormatBinary) unit_);
    }
    if (unitCase_ == 3) {
      output.writeMessage(3, (gpss.FormatCSV) unit_);
    }
    if (unitCase_ == 4) {
      output.writeMessage(4, (gpss.FormatDelimited) unit_);
    }
    if (unitCase_ == 5) {
      output.writeMessage(5, (gpss.FormatJSON) unit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unitCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (gpss.FormatAvro) unit_);
    }
    if (unitCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (gpss.FormatBinary) unit_);
    }
    if (unitCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (gpss.FormatCSV) unit_);
    }
    if (unitCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (gpss.FormatDelimited) unit_);
    }
    if (unitCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (gpss.FormatJSON) unit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.SourceDataFormat)) {
      return super.equals(obj);
    }
    gpss.SourceDataFormat other = (gpss.SourceDataFormat) obj;

    if (!getUnitCase().equals(other.getUnitCase())) return false;
    switch (unitCase_) {
      case 1:
        if (!getAvro()
            .equals(other.getAvro())) return false;
        break;
      case 2:
        if (!getBinary()
            .equals(other.getBinary())) return false;
        break;
      case 3:
        if (!getCsv()
            .equals(other.getCsv())) return false;
        break;
      case 4:
        if (!getDelimited()
            .equals(other.getDelimited())) return false;
        break;
      case 5:
        if (!getJson()
            .equals(other.getJson())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (unitCase_) {
      case 1:
        hash = (37 * hash) + AVRO_FIELD_NUMBER;
        hash = (53 * hash) + getAvro().hashCode();
        break;
      case 2:
        hash = (37 * hash) + BINARY_FIELD_NUMBER;
        hash = (53 * hash) + getBinary().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CSV_FIELD_NUMBER;
        hash = (53 * hash) + getCsv().hashCode();
        break;
      case 4:
        hash = (37 * hash) + DELIMITED_FIELD_NUMBER;
        hash = (53 * hash) + getDelimited().hashCode();
        break;
      case 5:
        hash = (37 * hash) + JSON_FIELD_NUMBER;
        hash = (53 * hash) + getJson().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.SourceDataFormat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.SourceDataFormat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.SourceDataFormat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.SourceDataFormat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.SourceDataFormat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.SourceDataFormat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.SourceDataFormat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.SourceDataFormat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.SourceDataFormat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.SourceDataFormat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.SourceDataFormat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.SourceDataFormat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.SourceDataFormat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * source data's format.
   * if there is an intermediate column inside Format,
   * then the source data will be transformed to the intermediate column.
   * If there is no source_column_name in Format,
   * then the column name will be the Target table column name,
   * and the source column data type should be matched with Target column type.
   * </pre>
   *
   * Protobuf type {@code gpss.SourceDataFormat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.SourceDataFormat)
      gpss.SourceDataFormatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_SourceDataFormat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_SourceDataFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.SourceDataFormat.class, gpss.SourceDataFormat.Builder.class);
    }

    // Construct using gpss.SourceDataFormat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      unitCase_ = 0;
      unit_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_SourceDataFormat_descriptor;
    }

    @java.lang.Override
    public gpss.SourceDataFormat getDefaultInstanceForType() {
      return gpss.SourceDataFormat.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.SourceDataFormat build() {
      gpss.SourceDataFormat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.SourceDataFormat buildPartial() {
      gpss.SourceDataFormat result = new gpss.SourceDataFormat(this);
      if (unitCase_ == 1) {
        if (avroBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = avroBuilder_.build();
        }
      }
      if (unitCase_ == 2) {
        if (binaryBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = binaryBuilder_.build();
        }
      }
      if (unitCase_ == 3) {
        if (csvBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = csvBuilder_.build();
        }
      }
      if (unitCase_ == 4) {
        if (delimitedBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = delimitedBuilder_.build();
        }
      }
      if (unitCase_ == 5) {
        if (jsonBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = jsonBuilder_.build();
        }
      }
      result.unitCase_ = unitCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.SourceDataFormat) {
        return mergeFrom((gpss.SourceDataFormat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.SourceDataFormat other) {
      if (other == gpss.SourceDataFormat.getDefaultInstance()) return this;
      switch (other.getUnitCase()) {
        case AVRO: {
          mergeAvro(other.getAvro());
          break;
        }
        case BINARY: {
          mergeBinary(other.getBinary());
          break;
        }
        case CSV: {
          mergeCsv(other.getCsv());
          break;
        }
        case DELIMITED: {
          mergeDelimited(other.getDelimited());
          break;
        }
        case JSON: {
          mergeJson(other.getJson());
          break;
        }
        case UNIT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.SourceDataFormat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.SourceDataFormat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int unitCase_ = 0;
    private java.lang.Object unit_;
    public UnitCase
        getUnitCase() {
      return UnitCase.forNumber(
          unitCase_);
    }

    public Builder clearUnit() {
      unitCase_ = 0;
      unit_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatAvro, gpss.FormatAvro.Builder, gpss.FormatAvroOrBuilder> avroBuilder_;
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     * @return Whether the avro field is set.
     */
    @java.lang.Override
    public boolean hasAvro() {
      return unitCase_ == 1;
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     * @return The avro.
     */
    @java.lang.Override
    public gpss.FormatAvro getAvro() {
      if (avroBuilder_ == null) {
        if (unitCase_ == 1) {
          return (gpss.FormatAvro) unit_;
        }
        return gpss.FormatAvro.getDefaultInstance();
      } else {
        if (unitCase_ == 1) {
          return avroBuilder_.getMessage();
        }
        return gpss.FormatAvro.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     */
    public Builder setAvro(gpss.FormatAvro value) {
      if (avroBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        avroBuilder_.setMessage(value);
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     */
    public Builder setAvro(
        gpss.FormatAvro.Builder builderForValue) {
      if (avroBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        avroBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     */
    public Builder mergeAvro(gpss.FormatAvro value) {
      if (avroBuilder_ == null) {
        if (unitCase_ == 1 &&
            unit_ != gpss.FormatAvro.getDefaultInstance()) {
          unit_ = gpss.FormatAvro.newBuilder((gpss.FormatAvro) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 1) {
          avroBuilder_.mergeFrom(value);
        }
        avroBuilder_.setMessage(value);
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     */
    public Builder clearAvro() {
      if (avroBuilder_ == null) {
        if (unitCase_ == 1) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 1) {
          unitCase_ = 0;
          unit_ = null;
        }
        avroBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     */
    public gpss.FormatAvro.Builder getAvroBuilder() {
      return getAvroFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     */
    @java.lang.Override
    public gpss.FormatAvroOrBuilder getAvroOrBuilder() {
      if ((unitCase_ == 1) && (avroBuilder_ != null)) {
        return avroBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 1) {
          return (gpss.FormatAvro) unit_;
        }
        return gpss.FormatAvro.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatAvro avro = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatAvro, gpss.FormatAvro.Builder, gpss.FormatAvroOrBuilder> 
        getAvroFieldBuilder() {
      if (avroBuilder_ == null) {
        if (!(unitCase_ == 1)) {
          unit_ = gpss.FormatAvro.getDefaultInstance();
        }
        avroBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.FormatAvro, gpss.FormatAvro.Builder, gpss.FormatAvroOrBuilder>(
                (gpss.FormatAvro) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 1;
      onChanged();;
      return avroBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatBinary, gpss.FormatBinary.Builder, gpss.FormatBinaryOrBuilder> binaryBuilder_;
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     * @return Whether the binary field is set.
     */
    @java.lang.Override
    public boolean hasBinary() {
      return unitCase_ == 2;
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     * @return The binary.
     */
    @java.lang.Override
    public gpss.FormatBinary getBinary() {
      if (binaryBuilder_ == null) {
        if (unitCase_ == 2) {
          return (gpss.FormatBinary) unit_;
        }
        return gpss.FormatBinary.getDefaultInstance();
      } else {
        if (unitCase_ == 2) {
          return binaryBuilder_.getMessage();
        }
        return gpss.FormatBinary.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     */
    public Builder setBinary(gpss.FormatBinary value) {
      if (binaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        binaryBuilder_.setMessage(value);
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     */
    public Builder setBinary(
        gpss.FormatBinary.Builder builderForValue) {
      if (binaryBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        binaryBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     */
    public Builder mergeBinary(gpss.FormatBinary value) {
      if (binaryBuilder_ == null) {
        if (unitCase_ == 2 &&
            unit_ != gpss.FormatBinary.getDefaultInstance()) {
          unit_ = gpss.FormatBinary.newBuilder((gpss.FormatBinary) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 2) {
          binaryBuilder_.mergeFrom(value);
        }
        binaryBuilder_.setMessage(value);
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     */
    public Builder clearBinary() {
      if (binaryBuilder_ == null) {
        if (unitCase_ == 2) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 2) {
          unitCase_ = 0;
          unit_ = null;
        }
        binaryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     */
    public gpss.FormatBinary.Builder getBinaryBuilder() {
      return getBinaryFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     */
    @java.lang.Override
    public gpss.FormatBinaryOrBuilder getBinaryOrBuilder() {
      if ((unitCase_ == 2) && (binaryBuilder_ != null)) {
        return binaryBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 2) {
          return (gpss.FormatBinary) unit_;
        }
        return gpss.FormatBinary.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatBinary binary = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatBinary, gpss.FormatBinary.Builder, gpss.FormatBinaryOrBuilder> 
        getBinaryFieldBuilder() {
      if (binaryBuilder_ == null) {
        if (!(unitCase_ == 2)) {
          unit_ = gpss.FormatBinary.getDefaultInstance();
        }
        binaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.FormatBinary, gpss.FormatBinary.Builder, gpss.FormatBinaryOrBuilder>(
                (gpss.FormatBinary) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 2;
      onChanged();;
      return binaryBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatCSV, gpss.FormatCSV.Builder, gpss.FormatCSVOrBuilder> csvBuilder_;
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     * @return Whether the csv field is set.
     */
    @java.lang.Override
    public boolean hasCsv() {
      return unitCase_ == 3;
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     * @return The csv.
     */
    @java.lang.Override
    public gpss.FormatCSV getCsv() {
      if (csvBuilder_ == null) {
        if (unitCase_ == 3) {
          return (gpss.FormatCSV) unit_;
        }
        return gpss.FormatCSV.getDefaultInstance();
      } else {
        if (unitCase_ == 3) {
          return csvBuilder_.getMessage();
        }
        return gpss.FormatCSV.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     */
    public Builder setCsv(gpss.FormatCSV value) {
      if (csvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        csvBuilder_.setMessage(value);
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     */
    public Builder setCsv(
        gpss.FormatCSV.Builder builderForValue) {
      if (csvBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        csvBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     */
    public Builder mergeCsv(gpss.FormatCSV value) {
      if (csvBuilder_ == null) {
        if (unitCase_ == 3 &&
            unit_ != gpss.FormatCSV.getDefaultInstance()) {
          unit_ = gpss.FormatCSV.newBuilder((gpss.FormatCSV) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 3) {
          csvBuilder_.mergeFrom(value);
        }
        csvBuilder_.setMessage(value);
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     */
    public Builder clearCsv() {
      if (csvBuilder_ == null) {
        if (unitCase_ == 3) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 3) {
          unitCase_ = 0;
          unit_ = null;
        }
        csvBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     */
    public gpss.FormatCSV.Builder getCsvBuilder() {
      return getCsvFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     */
    @java.lang.Override
    public gpss.FormatCSVOrBuilder getCsvOrBuilder() {
      if ((unitCase_ == 3) && (csvBuilder_ != null)) {
        return csvBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 3) {
          return (gpss.FormatCSV) unit_;
        }
        return gpss.FormatCSV.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatCSV csv = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatCSV, gpss.FormatCSV.Builder, gpss.FormatCSVOrBuilder> 
        getCsvFieldBuilder() {
      if (csvBuilder_ == null) {
        if (!(unitCase_ == 3)) {
          unit_ = gpss.FormatCSV.getDefaultInstance();
        }
        csvBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.FormatCSV, gpss.FormatCSV.Builder, gpss.FormatCSVOrBuilder>(
                (gpss.FormatCSV) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 3;
      onChanged();;
      return csvBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatDelimited, gpss.FormatDelimited.Builder, gpss.FormatDelimitedOrBuilder> delimitedBuilder_;
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     * @return Whether the delimited field is set.
     */
    @java.lang.Override
    public boolean hasDelimited() {
      return unitCase_ == 4;
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     * @return The delimited.
     */
    @java.lang.Override
    public gpss.FormatDelimited getDelimited() {
      if (delimitedBuilder_ == null) {
        if (unitCase_ == 4) {
          return (gpss.FormatDelimited) unit_;
        }
        return gpss.FormatDelimited.getDefaultInstance();
      } else {
        if (unitCase_ == 4) {
          return delimitedBuilder_.getMessage();
        }
        return gpss.FormatDelimited.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     */
    public Builder setDelimited(gpss.FormatDelimited value) {
      if (delimitedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        delimitedBuilder_.setMessage(value);
      }
      unitCase_ = 4;
      return this;
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     */
    public Builder setDelimited(
        gpss.FormatDelimited.Builder builderForValue) {
      if (delimitedBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        delimitedBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 4;
      return this;
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     */
    public Builder mergeDelimited(gpss.FormatDelimited value) {
      if (delimitedBuilder_ == null) {
        if (unitCase_ == 4 &&
            unit_ != gpss.FormatDelimited.getDefaultInstance()) {
          unit_ = gpss.FormatDelimited.newBuilder((gpss.FormatDelimited) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 4) {
          delimitedBuilder_.mergeFrom(value);
        }
        delimitedBuilder_.setMessage(value);
      }
      unitCase_ = 4;
      return this;
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     */
    public Builder clearDelimited() {
      if (delimitedBuilder_ == null) {
        if (unitCase_ == 4) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 4) {
          unitCase_ = 0;
          unit_ = null;
        }
        delimitedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     */
    public gpss.FormatDelimited.Builder getDelimitedBuilder() {
      return getDelimitedFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     */
    @java.lang.Override
    public gpss.FormatDelimitedOrBuilder getDelimitedOrBuilder() {
      if ((unitCase_ == 4) && (delimitedBuilder_ != null)) {
        return delimitedBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 4) {
          return (gpss.FormatDelimited) unit_;
        }
        return gpss.FormatDelimited.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatDelimited delimited = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatDelimited, gpss.FormatDelimited.Builder, gpss.FormatDelimitedOrBuilder> 
        getDelimitedFieldBuilder() {
      if (delimitedBuilder_ == null) {
        if (!(unitCase_ == 4)) {
          unit_ = gpss.FormatDelimited.getDefaultInstance();
        }
        delimitedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.FormatDelimited, gpss.FormatDelimited.Builder, gpss.FormatDelimitedOrBuilder>(
                (gpss.FormatDelimited) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 4;
      onChanged();;
      return delimitedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatJSON, gpss.FormatJSON.Builder, gpss.FormatJSONOrBuilder> jsonBuilder_;
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     * @return Whether the json field is set.
     */
    @java.lang.Override
    public boolean hasJson() {
      return unitCase_ == 5;
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     * @return The json.
     */
    @java.lang.Override
    public gpss.FormatJSON getJson() {
      if (jsonBuilder_ == null) {
        if (unitCase_ == 5) {
          return (gpss.FormatJSON) unit_;
        }
        return gpss.FormatJSON.getDefaultInstance();
      } else {
        if (unitCase_ == 5) {
          return jsonBuilder_.getMessage();
        }
        return gpss.FormatJSON.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     */
    public Builder setJson(gpss.FormatJSON value) {
      if (jsonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        jsonBuilder_.setMessage(value);
      }
      unitCase_ = 5;
      return this;
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     */
    public Builder setJson(
        gpss.FormatJSON.Builder builderForValue) {
      if (jsonBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        jsonBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 5;
      return this;
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     */
    public Builder mergeJson(gpss.FormatJSON value) {
      if (jsonBuilder_ == null) {
        if (unitCase_ == 5 &&
            unit_ != gpss.FormatJSON.getDefaultInstance()) {
          unit_ = gpss.FormatJSON.newBuilder((gpss.FormatJSON) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 5) {
          jsonBuilder_.mergeFrom(value);
        }
        jsonBuilder_.setMessage(value);
      }
      unitCase_ = 5;
      return this;
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     */
    public Builder clearJson() {
      if (jsonBuilder_ == null) {
        if (unitCase_ == 5) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 5) {
          unitCase_ = 0;
          unit_ = null;
        }
        jsonBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     */
    public gpss.FormatJSON.Builder getJsonBuilder() {
      return getJsonFieldBuilder().getBuilder();
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     */
    @java.lang.Override
    public gpss.FormatJSONOrBuilder getJsonOrBuilder() {
      if ((unitCase_ == 5) && (jsonBuilder_ != null)) {
        return jsonBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 5) {
          return (gpss.FormatJSON) unit_;
        }
        return gpss.FormatJSON.getDefaultInstance();
      }
    }
    /**
     * <code>.gpss.FormatJSON json = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gpss.FormatJSON, gpss.FormatJSON.Builder, gpss.FormatJSONOrBuilder> 
        getJsonFieldBuilder() {
      if (jsonBuilder_ == null) {
        if (!(unitCase_ == 5)) {
          unit_ = gpss.FormatJSON.getDefaultInstance();
        }
        jsonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gpss.FormatJSON, gpss.FormatJSON.Builder, gpss.FormatJSONOrBuilder>(
                (gpss.FormatJSON) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 5;
      onChanged();;
      return jsonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.SourceDataFormat)
  }

  // @@protoc_insertion_point(class_scope:gpss.SourceDataFormat)
  private static final gpss.SourceDataFormat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.SourceDataFormat();
  }

  public static gpss.SourceDataFormat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceDataFormat>
      PARSER = new com.google.protobuf.AbstractParser<SourceDataFormat>() {
    @java.lang.Override
    public SourceDataFormat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SourceDataFormat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SourceDataFormat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SourceDataFormat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.SourceDataFormat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

