// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface SubmitJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.SubmitJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * where does data flow to
   * </pre>
   *
   * <code>.gpss.Target target = 1;</code>
   * @return Whether the target field is set.
   */
  boolean hasTarget();
  /**
   * <pre>
   * where does data flow to
   * </pre>
   *
   * <code>.gpss.Target target = 1;</code>
   * @return The target.
   */
  gpss.Target getTarget();
  /**
   * <pre>
   * where does data flow to
   * </pre>
   *
   * <code>.gpss.Target target = 1;</code>
   */
  gpss.TargetOrBuilder getTargetOrBuilder();

  /**
   * <pre>
   * where is data come from
   * </pre>
   *
   * <code>.gpss.Source source = 2;</code>
   * @return Whether the source field is set.
   */
  boolean hasSource();
  /**
   * <pre>
   * where is data come from
   * </pre>
   *
   * <code>.gpss.Source source = 2;</code>
   * @return The source.
   */
  gpss.Source getSource();
  /**
   * <pre>
   * where is data come from
   * </pre>
   *
   * <code>.gpss.Source source = 2;</code>
   */
  gpss.SourceOrBuilder getSourceOrBuilder();

  /**
   * <pre>
   * how to transport data
   * </pre>
   *
   * <code>.gpss.Channel channel = 3;</code>
   * @return Whether the channel field is set.
   */
  boolean hasChannel();
  /**
   * <pre>
   * how to transport data
   * </pre>
   *
   * <code>.gpss.Channel channel = 3;</code>
   * @return The channel.
   */
  gpss.Channel getChannel();
  /**
   * <pre>
   * how to transport data
   * </pre>
   *
   * <code>.gpss.Channel channel = 3;</code>
   */
  gpss.ChannelOrBuilder getChannelOrBuilder();

  /**
   * <pre>
   * options to control the job
   * </pre>
   *
   * <code>.gpss.JobOption job_option = 4;</code>
   * @return Whether the jobOption field is set.
   */
  boolean hasJobOption();
  /**
   * <pre>
   * options to control the job
   * </pre>
   *
   * <code>.gpss.JobOption job_option = 4;</code>
   * @return The jobOption.
   */
  gpss.JobOption getJobOption();
  /**
   * <pre>
   * options to control the job
   * </pre>
   *
   * <code>.gpss.JobOption job_option = 4;</code>
   */
  gpss.JobOptionOrBuilder getJobOptionOrBuilder();
}
