// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

public interface TargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gpss.Target)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gpss.GPDBTarget gpdb = 1;</code>
   * @return Whether the gpdb field is set.
   */
  boolean hasGpdb();
  /**
   * <code>.gpss.GPDBTarget gpdb = 1;</code>
   * @return The gpdb.
   */
  gpss.GPDBTarget getGpdb();
  /**
   * <code>.gpss.GPDBTarget gpdb = 1;</code>
   */
  gpss.GPDBTargetOrBuilder getGpdbOrBuilder();

  public gpss.Target.UnitCase getUnitCase();
}
