// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpssjob.proto

package gpss;

/**
 * Protobuf type {@code gpss.UpdateMode}
 */
public final class UpdateMode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gpss.UpdateMode)
    UpdateModeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateMode.newBuilder() to construct.
  private UpdateMode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateMode() {
    filterExpression_ = "";
    matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    orderColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    updateCondition_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateMode();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateMode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            filterExpression_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              matchColumns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            matchColumns_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              updateColumns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            updateColumns_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              orderColumns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            orderColumns_.add(s);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            updateCondition_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        matchColumns_ = matchColumns_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        updateColumns_ = updateColumns_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        orderColumns_ = orderColumns_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gpss.Gpssjob.internal_static_gpss_UpdateMode_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gpss.Gpssjob.internal_static_gpss_UpdateMode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gpss.UpdateMode.class, gpss.UpdateMode.Builder.class);
  }

  public static final int FILTER_EXPRESSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object filterExpression_;
  /**
   * <pre>
   * filter expression is used for filter source data
   * </pre>
   *
   * <code>string filter_expression = 1;</code>
   * @return The filterExpression.
   */
  @java.lang.Override
  public java.lang.String getFilterExpression() {
    java.lang.Object ref = filterExpression_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filterExpression_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * filter expression is used for filter source data
   * </pre>
   *
   * <code>string filter_expression = 1;</code>
   * @return The bytes for filterExpression.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilterExpressionBytes() {
    java.lang.Object ref = filterExpression_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filterExpression_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATCH_COLUMNS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList matchColumns_;
  /**
   * <pre>
   * primary key for update/upsert/delete
   * </pre>
   *
   * <code>repeated string match_columns = 2;</code>
   * @return A list containing the matchColumns.
   */
  public com.google.protobuf.ProtocolStringList
      getMatchColumnsList() {
    return matchColumns_;
  }
  /**
   * <pre>
   * primary key for update/upsert/delete
   * </pre>
   *
   * <code>repeated string match_columns = 2;</code>
   * @return The count of matchColumns.
   */
  public int getMatchColumnsCount() {
    return matchColumns_.size();
  }
  /**
   * <pre>
   * primary key for update/upsert/delete
   * </pre>
   *
   * <code>repeated string match_columns = 2;</code>
   * @param index The index of the element to return.
   * @return The matchColumns at the given index.
   */
  public java.lang.String getMatchColumns(int index) {
    return matchColumns_.get(index);
  }
  /**
   * <pre>
   * primary key for update/upsert/delete
   * </pre>
   *
   * <code>repeated string match_columns = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the matchColumns at the given index.
   */
  public com.google.protobuf.ByteString
      getMatchColumnsBytes(int index) {
    return matchColumns_.getByteString(index);
  }

  public static final int UPDATE_COLUMNS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList updateColumns_;
  /**
   * <pre>
   * columns to be updated
   * </pre>
   *
   * <code>repeated string update_columns = 3;</code>
   * @return A list containing the updateColumns.
   */
  public com.google.protobuf.ProtocolStringList
      getUpdateColumnsList() {
    return updateColumns_;
  }
  /**
   * <pre>
   * columns to be updated
   * </pre>
   *
   * <code>repeated string update_columns = 3;</code>
   * @return The count of updateColumns.
   */
  public int getUpdateColumnsCount() {
    return updateColumns_.size();
  }
  /**
   * <pre>
   * columns to be updated
   * </pre>
   *
   * <code>repeated string update_columns = 3;</code>
   * @param index The index of the element to return.
   * @return The updateColumns at the given index.
   */
  public java.lang.String getUpdateColumns(int index) {
    return updateColumns_.get(index);
  }
  /**
   * <pre>
   * columns to be updated
   * </pre>
   *
   * <code>repeated string update_columns = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the updateColumns at the given index.
   */
  public com.google.protobuf.ByteString
      getUpdateColumnsBytes(int index) {
    return updateColumns_.getByteString(index);
  }

  public static final int ORDER_COLUMNS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList orderColumns_;
  /**
   * <pre>
   * columns used to sort rows, row with biggest value takes effect.
   * </pre>
   *
   * <code>repeated string order_columns = 4;</code>
   * @return A list containing the orderColumns.
   */
  public com.google.protobuf.ProtocolStringList
      getOrderColumnsList() {
    return orderColumns_;
  }
  /**
   * <pre>
   * columns used to sort rows, row with biggest value takes effect.
   * </pre>
   *
   * <code>repeated string order_columns = 4;</code>
   * @return The count of orderColumns.
   */
  public int getOrderColumnsCount() {
    return orderColumns_.size();
  }
  /**
   * <pre>
   * columns used to sort rows, row with biggest value takes effect.
   * </pre>
   *
   * <code>repeated string order_columns = 4;</code>
   * @param index The index of the element to return.
   * @return The orderColumns at the given index.
   */
  public java.lang.String getOrderColumns(int index) {
    return orderColumns_.get(index);
  }
  /**
   * <pre>
   * columns used to sort rows, row with biggest value takes effect.
   * </pre>
   *
   * <code>repeated string order_columns = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the orderColumns at the given index.
   */
  public com.google.protobuf.ByteString
      getOrderColumnsBytes(int index) {
    return orderColumns_.getByteString(index);
  }

  public static final int UPDATE_CONDITION_FIELD_NUMBER = 5;
  private volatile java.lang.Object updateCondition_;
  /**
   * <pre>
   * where condition
   * </pre>
   *
   * <code>string update_condition = 5;</code>
   * @return The updateCondition.
   */
  @java.lang.Override
  public java.lang.String getUpdateCondition() {
    java.lang.Object ref = updateCondition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updateCondition_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * where condition
   * </pre>
   *
   * <code>string update_condition = 5;</code>
   * @return The bytes for updateCondition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdateConditionBytes() {
    java.lang.Object ref = updateCondition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updateCondition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFilterExpressionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filterExpression_);
    }
    for (int i = 0; i < matchColumns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, matchColumns_.getRaw(i));
    }
    for (int i = 0; i < updateColumns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, updateColumns_.getRaw(i));
    }
    for (int i = 0; i < orderColumns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, orderColumns_.getRaw(i));
    }
    if (!getUpdateConditionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, updateCondition_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFilterExpressionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filterExpression_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < matchColumns_.size(); i++) {
        dataSize += computeStringSizeNoTag(matchColumns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMatchColumnsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < updateColumns_.size(); i++) {
        dataSize += computeStringSizeNoTag(updateColumns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUpdateColumnsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < orderColumns_.size(); i++) {
        dataSize += computeStringSizeNoTag(orderColumns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOrderColumnsList().size();
    }
    if (!getUpdateConditionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, updateCondition_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gpss.UpdateMode)) {
      return super.equals(obj);
    }
    gpss.UpdateMode other = (gpss.UpdateMode) obj;

    if (!getFilterExpression()
        .equals(other.getFilterExpression())) return false;
    if (!getMatchColumnsList()
        .equals(other.getMatchColumnsList())) return false;
    if (!getUpdateColumnsList()
        .equals(other.getUpdateColumnsList())) return false;
    if (!getOrderColumnsList()
        .equals(other.getOrderColumnsList())) return false;
    if (!getUpdateCondition()
        .equals(other.getUpdateCondition())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILTER_EXPRESSION_FIELD_NUMBER;
    hash = (53 * hash) + getFilterExpression().hashCode();
    if (getMatchColumnsCount() > 0) {
      hash = (37 * hash) + MATCH_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getMatchColumnsList().hashCode();
    }
    if (getUpdateColumnsCount() > 0) {
      hash = (37 * hash) + UPDATE_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateColumnsList().hashCode();
    }
    if (getOrderColumnsCount() > 0) {
      hash = (37 * hash) + ORDER_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderColumnsList().hashCode();
    }
    hash = (37 * hash) + UPDATE_CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateCondition().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gpss.UpdateMode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.UpdateMode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.UpdateMode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.UpdateMode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.UpdateMode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gpss.UpdateMode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gpss.UpdateMode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.UpdateMode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.UpdateMode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gpss.UpdateMode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gpss.UpdateMode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gpss.UpdateMode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gpss.UpdateMode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gpss.UpdateMode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gpss.UpdateMode)
      gpss.UpdateModeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gpss.Gpssjob.internal_static_gpss_UpdateMode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gpss.Gpssjob.internal_static_gpss_UpdateMode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gpss.UpdateMode.class, gpss.UpdateMode.Builder.class);
    }

    // Construct using gpss.UpdateMode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      filterExpression_ = "";

      matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      orderColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      updateCondition_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gpss.Gpssjob.internal_static_gpss_UpdateMode_descriptor;
    }

    @java.lang.Override
    public gpss.UpdateMode getDefaultInstanceForType() {
      return gpss.UpdateMode.getDefaultInstance();
    }

    @java.lang.Override
    public gpss.UpdateMode build() {
      gpss.UpdateMode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gpss.UpdateMode buildPartial() {
      gpss.UpdateMode result = new gpss.UpdateMode(this);
      int from_bitField0_ = bitField0_;
      result.filterExpression_ = filterExpression_;
      if (((bitField0_ & 0x00000001) != 0)) {
        matchColumns_ = matchColumns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.matchColumns_ = matchColumns_;
      if (((bitField0_ & 0x00000002) != 0)) {
        updateColumns_ = updateColumns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.updateColumns_ = updateColumns_;
      if (((bitField0_ & 0x00000004) != 0)) {
        orderColumns_ = orderColumns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.orderColumns_ = orderColumns_;
      result.updateCondition_ = updateCondition_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gpss.UpdateMode) {
        return mergeFrom((gpss.UpdateMode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gpss.UpdateMode other) {
      if (other == gpss.UpdateMode.getDefaultInstance()) return this;
      if (!other.getFilterExpression().isEmpty()) {
        filterExpression_ = other.filterExpression_;
        onChanged();
      }
      if (!other.matchColumns_.isEmpty()) {
        if (matchColumns_.isEmpty()) {
          matchColumns_ = other.matchColumns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMatchColumnsIsMutable();
          matchColumns_.addAll(other.matchColumns_);
        }
        onChanged();
      }
      if (!other.updateColumns_.isEmpty()) {
        if (updateColumns_.isEmpty()) {
          updateColumns_ = other.updateColumns_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureUpdateColumnsIsMutable();
          updateColumns_.addAll(other.updateColumns_);
        }
        onChanged();
      }
      if (!other.orderColumns_.isEmpty()) {
        if (orderColumns_.isEmpty()) {
          orderColumns_ = other.orderColumns_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureOrderColumnsIsMutable();
          orderColumns_.addAll(other.orderColumns_);
        }
        onChanged();
      }
      if (!other.getUpdateCondition().isEmpty()) {
        updateCondition_ = other.updateCondition_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gpss.UpdateMode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gpss.UpdateMode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object filterExpression_ = "";
    /**
     * <pre>
     * filter expression is used for filter source data
     * </pre>
     *
     * <code>string filter_expression = 1;</code>
     * @return The filterExpression.
     */
    public java.lang.String getFilterExpression() {
      java.lang.Object ref = filterExpression_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filterExpression_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * filter expression is used for filter source data
     * </pre>
     *
     * <code>string filter_expression = 1;</code>
     * @return The bytes for filterExpression.
     */
    public com.google.protobuf.ByteString
        getFilterExpressionBytes() {
      java.lang.Object ref = filterExpression_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterExpression_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * filter expression is used for filter source data
     * </pre>
     *
     * <code>string filter_expression = 1;</code>
     * @param value The filterExpression to set.
     * @return This builder for chaining.
     */
    public Builder setFilterExpression(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filterExpression_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filter expression is used for filter source data
     * </pre>
     *
     * <code>string filter_expression = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilterExpression() {
      
      filterExpression_ = getDefaultInstance().getFilterExpression();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filter expression is used for filter source data
     * </pre>
     *
     * <code>string filter_expression = 1;</code>
     * @param value The bytes for filterExpression to set.
     * @return This builder for chaining.
     */
    public Builder setFilterExpressionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filterExpression_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMatchColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        matchColumns_ = new com.google.protobuf.LazyStringArrayList(matchColumns_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @return A list containing the matchColumns.
     */
    public com.google.protobuf.ProtocolStringList
        getMatchColumnsList() {
      return matchColumns_.getUnmodifiableView();
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @return The count of matchColumns.
     */
    public int getMatchColumnsCount() {
      return matchColumns_.size();
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @param index The index of the element to return.
     * @return The matchColumns at the given index.
     */
    public java.lang.String getMatchColumns(int index) {
      return matchColumns_.get(index);
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the matchColumns at the given index.
     */
    public com.google.protobuf.ByteString
        getMatchColumnsBytes(int index) {
      return matchColumns_.getByteString(index);
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @param index The index to set the value at.
     * @param value The matchColumns to set.
     * @return This builder for chaining.
     */
    public Builder setMatchColumns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchColumnsIsMutable();
      matchColumns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @param value The matchColumns to add.
     * @return This builder for chaining.
     */
    public Builder addMatchColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchColumnsIsMutable();
      matchColumns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @param values The matchColumns to add.
     * @return This builder for chaining.
     */
    public Builder addAllMatchColumns(
        java.lang.Iterable<java.lang.String> values) {
      ensureMatchColumnsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, matchColumns_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatchColumns() {
      matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * primary key for update/upsert/delete
     * </pre>
     *
     * <code>repeated string match_columns = 2;</code>
     * @param value The bytes of the matchColumns to add.
     * @return This builder for chaining.
     */
    public Builder addMatchColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMatchColumnsIsMutable();
      matchColumns_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUpdateColumnsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        updateColumns_ = new com.google.protobuf.LazyStringArrayList(updateColumns_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @return A list containing the updateColumns.
     */
    public com.google.protobuf.ProtocolStringList
        getUpdateColumnsList() {
      return updateColumns_.getUnmodifiableView();
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @return The count of updateColumns.
     */
    public int getUpdateColumnsCount() {
      return updateColumns_.size();
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @param index The index of the element to return.
     * @return The updateColumns at the given index.
     */
    public java.lang.String getUpdateColumns(int index) {
      return updateColumns_.get(index);
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the updateColumns at the given index.
     */
    public com.google.protobuf.ByteString
        getUpdateColumnsBytes(int index) {
      return updateColumns_.getByteString(index);
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @param index The index to set the value at.
     * @param value The updateColumns to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateColumns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUpdateColumnsIsMutable();
      updateColumns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @param value The updateColumns to add.
     * @return This builder for chaining.
     */
    public Builder addUpdateColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUpdateColumnsIsMutable();
      updateColumns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @param values The updateColumns to add.
     * @return This builder for chaining.
     */
    public Builder addAllUpdateColumns(
        java.lang.Iterable<java.lang.String> values) {
      ensureUpdateColumnsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, updateColumns_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateColumns() {
      updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns to be updated
     * </pre>
     *
     * <code>repeated string update_columns = 3;</code>
     * @param value The bytes of the updateColumns to add.
     * @return This builder for chaining.
     */
    public Builder addUpdateColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUpdateColumnsIsMutable();
      updateColumns_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList orderColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOrderColumnsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        orderColumns_ = new com.google.protobuf.LazyStringArrayList(orderColumns_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @return A list containing the orderColumns.
     */
    public com.google.protobuf.ProtocolStringList
        getOrderColumnsList() {
      return orderColumns_.getUnmodifiableView();
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @return The count of orderColumns.
     */
    public int getOrderColumnsCount() {
      return orderColumns_.size();
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @param index The index of the element to return.
     * @return The orderColumns at the given index.
     */
    public java.lang.String getOrderColumns(int index) {
      return orderColumns_.get(index);
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the orderColumns at the given index.
     */
    public com.google.protobuf.ByteString
        getOrderColumnsBytes(int index) {
      return orderColumns_.getByteString(index);
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @param index The index to set the value at.
     * @param value The orderColumns to set.
     * @return This builder for chaining.
     */
    public Builder setOrderColumns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOrderColumnsIsMutable();
      orderColumns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @param value The orderColumns to add.
     * @return This builder for chaining.
     */
    public Builder addOrderColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOrderColumnsIsMutable();
      orderColumns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @param values The orderColumns to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrderColumns(
        java.lang.Iterable<java.lang.String> values) {
      ensureOrderColumnsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, orderColumns_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderColumns() {
      orderColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns used to sort rows, row with biggest value takes effect.
     * </pre>
     *
     * <code>repeated string order_columns = 4;</code>
     * @param value The bytes of the orderColumns to add.
     * @return This builder for chaining.
     */
    public Builder addOrderColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOrderColumnsIsMutable();
      orderColumns_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object updateCondition_ = "";
    /**
     * <pre>
     * where condition
     * </pre>
     *
     * <code>string update_condition = 5;</code>
     * @return The updateCondition.
     */
    public java.lang.String getUpdateCondition() {
      java.lang.Object ref = updateCondition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateCondition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * where condition
     * </pre>
     *
     * <code>string update_condition = 5;</code>
     * @return The bytes for updateCondition.
     */
    public com.google.protobuf.ByteString
        getUpdateConditionBytes() {
      java.lang.Object ref = updateCondition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateCondition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * where condition
     * </pre>
     *
     * <code>string update_condition = 5;</code>
     * @param value The updateCondition to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updateCondition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * where condition
     * </pre>
     *
     * <code>string update_condition = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateCondition() {
      
      updateCondition_ = getDefaultInstance().getUpdateCondition();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * where condition
     * </pre>
     *
     * <code>string update_condition = 5;</code>
     * @param value The bytes for updateCondition to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updateCondition_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gpss.UpdateMode)
  }

  // @@protoc_insertion_point(class_scope:gpss.UpdateMode)
  private static final gpss.UpdateMode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gpss.UpdateMode();
  }

  public static gpss.UpdateMode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateMode>
      PARSER = new com.google.protobuf.AbstractParser<UpdateMode>() {
    @java.lang.Override
    public UpdateMode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateMode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateMode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateMode> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gpss.UpdateMode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

